### ISSUE TITLE
Improving the docs

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#114]
I'm not sure that it was a good idea to put the docs as part of the API (well, I think that still can be useful, but not nearly as useful as having a web form for the docs).  I think we should make sure that all of the tabe descriptions listed in `/docs` are also listed for the corresponding route/table in https://ropensci.github.io/fishbaseapidocs/ , and perhaps more concisely in an HTML table on the landing page.  I get emails pretty frequently saying things like: "would you be able to add the FAO Areas data?" and there's really no nice readable page to point people to say: look, the FAO Areas table is right there under `faoareas`

**Comment by sckott** [comment]
good pts. 

We can redirect `/docs` to https://ropensci.github.io/fishbaseapidocs/ if you want?

> and perhaps more concisely in an HTML table on the landing page

landing page of https://ropensci.github.io/fishbaseapidocs or of fishbase.ropensci.org ?
