### ISSUE TITLE
Download SQL FILE

### ISSUE THREAD

**Issue by fagnerabsynth** [ropensci/fishbaseapi#121]
Hi,

I'm trying to do a sql dump to implement and translate to my language and append to a mobile project.

But every time return returns: 
Can not connect to MySQL server on " Your IP", the server must be off.

Is there any other way to get the dump?

or I have to do the one-by-one registry as per the query in my App.

If anyone can help me, I appreciate it.

Thank you!

**Comment by sckott** [comment]
What did you do that generated that error?  Do you want a dump of the entire database? If so, we can not do that.

**Comment by fagnerabsynth** [comment]
When I use import.sh this error appears.

**Comment by sckott** [comment]
Apologies. that's only meant for us to import dumps of the fishbase database on our server.

**Comment by fagnerabsynth** [comment]
ok,

Thank you!

**Comment by sckott** [comment]
thanks for your interest.
