### ISSUE TITLE
add route: /taxa/:id

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#129]
via feedback on readme.io docs

**Comment by sckott** [comment]
https://fishbaseapi.readme.io/v1.0/discuss/5c6da6a288b4960045af003e

**Comment by frmichel** [comment]
Hi @sckott, just wondering if you had time to think about this issue, and if there is any planned date when the service could be implemented?

Thx,
   Franck.

**Comment by sckott** [comment]
Thanks for the bump @frmichel hopefully soonish. do you plan to use the API directly or through the rfishbase pkg? if the latter, we'd need to implement it there as well

**Comment by frmichel** [comment]
Hi @sckott, we use the API directly, not the pkg.

**Comment by cboettig** [comment]
@frmichel Thanks for the ping here.  Can you give us a little more context on your use case(s)?  

You can already get all the taxon ids in the R package by doing something like `rfishbase::species()` (or `rfishbase::load_taxa()` for the full taxonomy).  If you are trying to avoid R, you can also just get these tables directly, e.g. from the official archive: https://doi.org/10.5281/zenodo.1421047

**Comment by sckott** [comment]
thanks @frmichel

**Comment by sckott** [comment]
@frmichel route added, try it out https://fishbaseapi.readme.io/v1.0/docs/taxa-by-id

**Comment by frmichel** [comment]
> @frmichel route added, try it out https://fishbaseapi.readme.io/v1.0/docs/taxa-by-id

Excellent! Thank you guys, that will be very helpful.

> @frmichel Can you give us a little more context on your use case(s)?

@cboettig, we are currently working ona solution to compare the information in TAXREF, the French taxonomic register, with other data sources such as FishBase, GBIF, WoRMS, Index Fungorum etc. For now, the comparison pertains to taxonomy, synonyms, classification and habitats. Later, we intend to extend this to traits with EoL etc.

To do so, we wrap services of each of the Web APIs in what we call [SPARQL micro-services](https://github.com/frmichel/sparql-micro-service). This way, we have a uniform and easy-to-compare representation for data coming from multiple data sources. Hence our need for a "taxa by id" service in FishBase.

In case you are interested, I presented a [demo](http://sms.i3s.unice.fr/demo-sms?param=Delphinapterus+leucas) last year at the TDWG conference about a possible use case of these SPARQL micro-services.

Franck.

**Comment by cboettig** [comment]
Thanks @frmichel that sounds very cool indeed!  I'll take a look at the demo too
