### ISSUE TITLE
Synonyms

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#13]
We now have the `/taxa` endpoint, but one thing that's left out is the `synonyms` table and its data. Perhaps that should be a separate endpoint ? @cboettig

**Comment by cboettig** [comment]
good point. Given that there will be multiple synonyms per species, maybe this should be a separate endpoint.  Then a species query can hit this first to resolve from a synonym to the preferred name.

**Comment by sckott** [comment]
cool, sounds good

**Comment by sckott** [comment]
closed in 906f6a894174021d4a17e597e4292e836268f4ee
