### ISSUE TITLE
Undocumented parameters in service synonyms?

### ISSUE THREAD

**Issue by frmichel** [ropensci/fishbaseapi#132]
Hi all,

According to the [documentation](https://fishbaseapi.readme.io/docs/synonyms), the `synonyms` service returns all synonyms at once, whihin a range set by offset and limit. 

Yet, we found out that it can be queried with parameters, e.g.:
- querying this service with a `SynCode` seems to return information about exactly one synonym (e.g. https://fishbase.ropensci.org/synonyms?synCode=25357)
- while querying it with a `SpecCode` seems to return information about all the synonyms associated with one species (e.g. https://fishbase.ropensci.org/synonyms?specCode=4875)

Is this correct? Can we use the service safely this way even though this is not documented?
Or in other words, is it just a lack in the documentation, but this way or querying the service will be maintained in the long time?

Thx,
   Franck.

**Comment by frmichel** [comment]
Note that at the time of writing the 'Try it out' option on https://fishbaseapi.readme.io/docs/synonyms returns an error 500 (see https://fishbaseapi.readme.io/v1.0/discuss/5ca5d0c520af39005c7cc328).

**Comment by sckott** [comment]
i think try it out is working now, try it again and let me know

**Comment by sckott** [comment]
you're correct that it's a lack of documentation. we allow queries on any of the keys in the json response, I think for all routes except `/taxa` perhaps. 

I've updated the docs just for this route: https://fishbaseapi.readme.io/v1.0/docs/synonyms Thoughts on that? If that's clear enough I'll add it to the rest of the routes as applicable.

We have no plans of changing this ability to query on any keys in the response

**Comment by frmichel** [comment]
Hi @sckott, thx for the documentation update, that's pretty clear I guess, and definitely handy ;)

**Comment by sckott** [comment]
okay, thanks. I'll fill out the rest of the documentation soon

**Comment by sckott** [comment]
docs updated
