### ISSUE TITLE
Egg tables

### ISSUE THREAD

**Issue by fbsut1** [ropensci/fishbaseapi#133]
I can't find Egg or EggDevelopment tables through commands (https://www.fishbase.in/manual/english/FishBaseThe_EGGS_Table.htm
https://www.fishbase.in/manual/english/FishBaseThe_eggdev_Table.htm)
I'm looking for egg diameter and a few other egg characteristics.
Thanks!

**Comment by sckott** [comment]
are you trying to get data from the Fishbase website or from the API?

**Comment by sckott** [comment]
for the API try https://fishbase.ropensci.org/eggs/

**Comment by fbsut1** [comment]
Thanks. Apologies for novice question, but how can I get egg data for a subset of species (i.e. all the species in a single family). I can't figure out how to specify species of interest with API. (Or is there a function in Rfishbase that corresponds to Egg Table?)

**Comment by cboettig** [comment]
@fbsut1 Looks like the `eggs` table isn't exposed in the `rfishbase` function list, but you can easily create the endpoint manually; e.g.

```
library(rfishbase)
eggs <- rfishbase:::endpoint("eggs")
eggs()
```

**Comment by fbsut1** [comment]
Thanks!
