### ISSUE TITLE
status 500 for `/species?limit=10`

### ISSUE THREAD

**Issue by aengl** [ropensci/fishbaseapi#134]
BACKTRACE:
```
/opt/sinatra/api.rb in block in <class:API>
      ver_h = ver_h.split(',').keep_if { |x| x.match(/application\/vnd\.ropensci/) }[0]
```

Variable | Value
-- | --
HTTP_ACCEPT_ENCODING | gzip, deflate
HTTP_CONNECTION | close
HTTP_HOST | fishbase.ropensci.org
HTTP_USER_AGENT | got/9.6.0 (https://github.com/sindresorhus/got)
HTTP_VERSION | HTTP/1.1
HTTP_X_FORWARDED_FOR | 14.207.69.144
HTTP_X_FORWARDED_PROTO | https
HTTP_X_REAL_IP | 14.207.69.144
PATH_INFO | /species
QUERY_STRING | limit=10
REMOTE_ADDR | 172.17.0.1
REQUEST_METHOD | GET
REQUEST_PATH | /species
REQUEST_URI | /species?limit=10
SCRIPT_NAME |  
SERVER_NAME | fishbase.ropensci.org
SERVER_PORT | 443
SERVER_PROTOCOL | HTTP/1.1
SERVER_SOFTWARE | Unicorn 5.3.1
rack.errors | #<Object:0x00556ee1cd82a0>
rack.hijack | #<Proc:0x00556ef5876fb8@/usr/local/bundle/gems/rack-2.0.3/lib/rack/lint.rb:525>
rack.hijack? | true
rack.input | #<Rack::Lint::InputWrapper:0x00556ef5876d38 @input=#<StringIO:0x00556ee00f8120>>
rack.logger | #<Logger:0x00556ef5876b58 @progname=nil, @level=1, @default_formatter=#<Logger::Formatter:0x00556ef5876b30 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00556ef5876ae0 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<Rack::Lint::ErrorWrapper:0x00556ef5876d10 @error=#<IO:<STDERR>>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x00556ef5876ab8 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00556ef5876a68>>>>
rack.multiprocess | true
rack.multithread | false
rack.request.cookie_hash | {}
rack.request.query_hash | {"limit"=>"10"}
rack.request.query_string | limit=10
rack.run_once | false
rack.tempfiles | []
rack.url_scheme | https
rack.version | [1, 2]
sinatra.accept | [#<Sinatra::Request::AcceptEntry:0x00556ee51b3650 @entry="*/*", @type="*/*", @params={}, @q=1.0>]
sinatra.commonlogger | true
sinatra.error | #<NoMethodError: undefined method `split' for nil:NilClass>
sinatra.error.params | {"limit"=>"10", "captures"=>[]}
unicorn.socket | #<Unicorn::TCPClient:fd 7>

[500.html.zip](https://github.com/ropensci/fishbaseapi/files/3443642/500.html.zip)

**Comment by sckott** [comment]
Please share the complete request you performed that caused the error. Including complete url and request headers

**Comment by aengl** [comment]
Using
```js
const got = require('got');
const fs = require('fs');
(async () => {
  try {
    await got('https://fishbase.ropensci.org/species?limit=10');
  } catch (error) {
    console.error({
      host: error.host,
      path: error.path,
      url: error.url,
      statusCode: error.statusCode,
      headers: error.headers,
    });
  }
})();
```
prints
```sh
♦ node fishbase.js
{
  host: 'fishbase.ropensci.org',
  path: '/species?limit=10',
  url: 'https://fishbase.ropensci.org/species?limit=10',
  statusCode: 500,
  headers: {
    'content-encoding': 'gzip',
    'content-type': 'text/html',
    date: 'Mon, 29 Jul 2019 18:29:50 GMT',
    server: 'Caddy',
    vary: 'Accept-Encoding',
    connection: 'close',
    'transfer-encoding': 'chunked'
  }
}
```

**Comment by aengl** [comment]
The error is caused by the request not accepting a JSON response it would seem. I can of course resolve that on my end, but the 500 is probably not intentional 😃

**Comment by sckott** [comment]
Thx, those are response headers, what do request headers look like. 

It looks like we're failiing where we look for the users Accept header but if it's nil, then we fail.

**Comment by aengl** [comment]
Ah, apologies. The request headers are simply:
```
{
  'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
  'accept-encoding': 'gzip, deflate'
}
```

**Comment by sckott** [comment]
thx, it's the empty `Accept` header that I didn't account for, fixing it now

**Comment by sckott** [comment]
we're back up, try it again, should work now

**Comment by aengl** [comment]
Yes, can confirm that it works now. Thank you for the swift fix! 👍
