### ISSUE TITLE
accessing identification keys in the api

### ISSUE THREAD

**Issue by leipzig** [ropensci/fishbaseapi#139]
Thanks for developing this API. I am working with BGNN, an NSF-funded project to develop neural networks for automated fish morphology. I would like to access the identification keys [https://www.fishbase.se/keys/allkeys.php](https://www.fishbase.se/keys/allkeys.php) that are in FishBase as structured data. I would like to be able to transform these from a "wizard-type" dialog to a feature table.

Not sure if these are in the database dump FishBase kindly provided to rOpensci, or if there is any interest in serving these as a web service. They are quite disordered right now.

**Comment by sckott** [comment]
Thanks for your message. 

Yes, we do have that data in a table in the database dumps.  @cboettig do you think we need to ask Fishbase if we can expose that or should we just do it?

> I would like to be able to transform these from a "wizard-type" dialog to a feature table.

not sure i follow. what is "wizard type"?

**Comment by cboettig** [comment]
Thanks @leipzig .   You can find tables exported from the SQL as flat csv files here: https://github.com/ropensci/rfishbase/releases .  As you probably know, they aren't particularly transparent / well-organized; in particular, you will find different capitalization for some id/key columns (`SpecCode` vs `Speccode`).  Still, this situation with the FishBase dumps is of course very understandable in a database that has been maintained for so many decades of change in underlying technology, expansion of information, limited funding, and wasn't originally intended for this kind of direct or API access, so I guess we shouldn't complain :-)

I'm also not sure what that identification keys table is that you've linked, or what you mean by "wizar-type" dialogue, but hopefully a bit of splunking in those tables helps you locate what you're after?

**Comment by leipzig** [comment]
By “wizard” I mean the Fishbase identification keys are meant to be followed by people trying to identify fish using a wizard ui process. E.g a “1. scaly-backed, go to step 5. 5. If more than 10cm go to step 8”. Obviously, this won’t work for machine learning. I’ll check out the release. Thanks for your quick responses!
