### ISSUE TITLE
Add a function to ping / reconnect the mysql server?

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#14]
Hey @sckott ,

I'm having some stability problems with the mysql server still.  It seems that often it is sufficient to ping the server to re-establish the connection. Could we add an endpoint that would just ping the server? (Would at least be handy for debugging).  Might need to explore some more tricks to babysit the mysql server too.

**Comment by sckott** [comment]
@cboettig hmmm, does `/heartbeat` work?  weird, i've not had that problem running locally, are we sure it's a mysql server problem?

**Comment by cboettig** [comment]
@sckott `/heartbeat` will execute successfully whether or not the mysql connection is live, as long as sinatra / webrick is still up. 

Right, I don't think you'll get this error because when you're running locally your connecting to mysql over the default unix socket, `/var/run/mysqld/mysqld.sock`, rather than over a network `tcp`. (See the extra lines I have at the top of `api.rb`).  Even if we weren't using docker containers to deploy, connecting to the mysql server over `tcp` is probably the most common implementation on the server side; and also allows the mysql server to be run from a different machine if necessary).

**Comment by sckott** [comment]
@cboettig are we good on this now? solved?

**Comment by cboettig** [comment]
I think so. we'll see if the server is still up tomorrow, but we can close for now.
