### ISSUE TITLE
Add documentation to fields

### ISSUE THREAD

**Issue by mackelito** [ropensci/fishbaseapi#141]
There are fields like "Expert: 42," what does that mean?
To make it easier to understand the api responses I think some additional documentation would be helpful :)

**Comment by sckott** [comment]
Thanks @mackelito for the issue. 

We just serve the data over the API, we are not affiliated with Fishbase in any way - I don't know of any place to get details on each of the fields returned by any given database table - it may be somewhere, but we don't know where that is. 

We do have docs routes https://fishbase.ropensci.org/docs/ e.g., https://fishbase.ropensci.org/docs/ecology/  Those could have details on what each field means, and possibly units as well, when applicable. However, we don't have the time to curate that information. If someone or someone's wanted to do that, that would be great.
