### ISSUE TITLE
[Question] Is there any way to detect compatibility between fishes?

### ISSUE THREAD

**Issue by adityakrshnn** [ropensci/fishbaseapi#142]
I was wondering if some field could indicate the fish's behaviour towards other types of fishes. Is there some endpoint that would give this info?

**Comment by sckott** [comment]
Thanks for your question. Unfortunately I don't know anything off the top that I know of - but i'm not super familiar with all variables anyway as we just provide the data (we aren't fish people, not affiliated with fishbase). 

I'd suggest looking around on the https://www.fishbase.de/ website - find some variable you'd like to use - let us know and we'll see if we have it here in the API

**Comment by adityakrshnn** [comment]
Oh. I didn't find any such info on Fishbase as well. Closing this for now.

**Comment by sckott** [comment]
Is this the kind of thing you're looking for?

https://www.fishbase.de/summary/Parachromis-dovii.html 

> Produces about 1000-1500 eggs. __Altruism with males of other species while tending the young__. This updates previous informations from Ref. 7335. Min. 1000 eggs, sexual maturity is reached at 15 months and 20 cm (Ref. 2060).

Find that species with /species route

https://fishbase.ropensci.org/species/?Genus=Parachromis&Species=dovii

Then find that life cycle info in the /reproduc route given that species code

https://fishbase.ropensci.org/reproduc/?SpecCode=6413

**Comment by adityakrshnn** [comment]
While this is very helpful, I was actually looking for info on aquarium compatibility. Something like Cichlids are aggressive and territorial and hence would not be a suitable tank mate for Koi and other Carps. However, Cichlids do well with Loaches, Catfish and Tetras. Something to that extent.

**Comment by sckott** [comment]
Hmm, ive no idea. 

I found those links above by googling fishbase and various terms. You might try that since fishbase is indexed by google/etc. so you might be able to find something useful. Maybe you've already tried that though
