### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by alessandro-russo** [ropensci/fishbaseapi#145]
Hi all,

as also reported [here](https://fishbaseapi.readme.io/v1.0/discuss/61014453601bfe001c6fd897) by others, since weeks any attempt to access the API results in a `502 Bad Gateway` response from the server.

I hope this is a temporary issue and that the API is still maintained!

Thanks!!!

**Comment by eeeggg** [comment]
Hi @sckott sorry to bug you but I noted your responses to other issues for this project in the past and I figured I'd mention you directly to see if you had an estimate as to when the API would be back online.

Anything I can do to help get it back up and running?

**Comment by sckott** [comment]
@eeeggg Sorry, but i've changed jobs and this API is no longer something I work on. @cboettig is the one to ask, but I'm guessing he's not interested in getting it back up 

if Carl's not interested, someone else may want to maintain the API - can get you in touch with Fishbase if you or others want to do it

**Comment by eeeggg** [comment]
@sckott @cboettig I'm totally willing to take on this API. I've already been in contact with Q-Quatics/FishBase over the last several months and I believe they want it up as badly as I do... so who do I talk to about supporting this project? rOpenSci?

**Comment by sckott** [comment]
@eeeggg email me at sckott@fastmail.com and then I'll email the fishbase folks and then we can take it from there.

**Comment by alessandro-russo** [comment]
Thanks @eeeggg and @sckott for clarifying the situation!

@eeeggg: if you need any help with your plan of taking over the API, I'll be happy to contribute!

**Comment by TomBell95** [comment]
Hi guys - Is there any update as to whether this API will be back up? Thanks

**Comment by sckott** [comment]
It was decided it wouldn't come back online. I believe (@cboettig correct me if i'm wrong) that the flat file approach will still be available moving forward - see https://github.com/ropensci/rfishbase/releases

**Comment by cboettig** [comment]
What we could do though is host the flat files from the old endpoints, rather than serving JSON responses you'd get the full table as (compressed) csv, but since most tables are less than one MB it wouldn't increase latency I think.

**Comment by TomBell95** [comment]
That would be great if possible? Thanks for the quick responses guys!

**Comment by jannmacutay** [comment]
Thanks for this info. Been waiting for this. Too sad the API is no longer available.

**Comment by rbasdfgit** [comment]
1) Is there any news about the API?
2) Are these the tables/the latest data from where one can pick ? https://github.com/ropensci/rfishbase/releases

**Comment by cboettig** [comment]
Thanks for the ping, slowly reviving things here.  

There's now a static API, e.g. https://fishbase.ropensci.org/fishbase/ and https://fishbase.ropensci.org/sealifebase/ respectively will give you a list of currently available tables, as parquet data files.  You can access any individual table directly:

https://fishbase.ropensci.org/fishbase/abundance.parquet


There is no longer a dedicated server running SQL + custom ruby code to provide endpoints to which accept individual species queries and return small JSON.  The full parquet files are already small enough, so the earlier workflow was needlessly inefficient and created a large attack surface of publicly facing hand-written interface code that is not sustainable to maintain.  The idea here is that this static model relies only professionally maintained and highly standard interfaces, i.e. http and parquet files.  


Currently this does not host archived versions.  full provenance information is available in the provenance records: https://github.com/ropensci/rfishbase/blob/master/inst/prov/fb.prov.  Content-based identifier resolution can be used to recover these files from a variety of archival points.

**Comment by cboettig** [comment]
The API has migrated to S3, see https://github.com/ropensci/fishbaseapi/blob/master/README.md
