### ISSUE TITLE
REnew SSL licence?

### ISSUE THREAD

**Issue by cltj** [ropensci/fishbaseapi#146]
Getting this when trying to access the api (all calls):

Error: write EPROTO 139909459205448:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 80

**Comment by alessandro-russo** [comment]
Hi @cltj, as of today the API is no longer actively maintaned (see #145 and in particular [here](https://github.com/ropensci/fishbaseapi/issues/145#issuecomment-1022376716)).

**Comment by cboettig** [comment]
The API has migrated to S3, see https://github.com/ropensci/fishbaseapi/blob/master/README.md
