### ISSUE TITLE
Where can we download the fbapp.sql file

### ISSUE THREAD

**Issue by ccaspanello** [ropensci/fishbaseapi#149]
I've been looking around FishBase and can't find the link; would you guys happen to know? Perhaps providing download instructions in the ReadMe

**Comment by cboettig** [comment]
The API has migrated to S3, in parquet format.  SQL dump is not publicly distributed.

**Comment by cboettig** [comment]
see README updates https://github.com/ropensci/fishbaseapi/blob/master/README.md

**Comment by ccaspanello** [comment]
Woa!  That is awesome news.  Thank you!
