### ISSUE TITLE
Use stats/logging

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#15]
Just thinking it might be valuable to be able to compute some basic metrics of use for the FishBase team to monitor traffic; e.g. which endpoints are getting hit, how often, perhaps from what geographic areas.  Have you looked into this?

**Comment by sckott** [comment]
@cboettig not yet, looks like sinatra has a built in logging tool http://www.sinatrarb.com/intro.html#Logging - not sure yet how to access those, maybe storing them in something like logstash http://logstash.net/docs/1.4.2/

**Comment by sckott** [comment]
@cboettig Okay, testing locally so far, not pushing up yet, but looks like this will work pretty easily
- use built in Sinatra logging
- Save logs to a file (or could use more advanced save to redis, or other options, but file seems nice and simple)
- Push logs into Elasticsearch via Logstash
- world domination! 

e.g. now in elasticsearch we can do something like:

```
http 'http://localhost:9200/logstash-2015.02.10/_search?q=timestamp&size=3' | jq ' .hits | .hits'

{
  "_source": {
    "path": "/Users/sacmac/fishbaseapi2.log",
    "host": "Scotts-MBP",
    "@timestamp": "2015-02-10T17:39:06.956Z",
    "@version": "1",
    "message": "{\"@timestamp\":\"2015-02-10T17:39:06Z\",\"@fields\":{\"method\":\"GET\",\"path\":\"/\",\"status\":\"302\",\"size\":\"-\",\"duration\":0.000986}}"
  },
  "_score": 0.34636837,
  "_id": "AUt0krZS-gODqlF1zfdY",
  "_type": "logs",
  "_index": "logstash-2015.02.10"
}
{
  "_source": {
    "path": "/Users/sacmac/fishbaseapi2.log",
    "host": "Scotts-MBP",
    "@timestamp": "2015-02-10T17:38:03.690Z",
    "@version": "1",
    "message": "{\"@timestamp\":\"2015-02-10T17:38:03Z\",\"@fields\":{\"method\":\"GET\",\"path\":\"/taxa/\",\"status\":\"200\",\"size\":\"1225\",\"duration\":0.00736}}"
  },
  "_score": 0.2886403,
  "_id": "AUt0kb94-gODqlF1zfdU",
  "_type": "logs",
  "_index": "logstash-2015.02.10"
}
{
  "_source": {
    "path": "/Users/sacmac/fishbaseapi2.log",
    "host": "Scotts-MBP",
    "@timestamp": "2015-02-10T17:38:07.709Z",
    "@version": "1",
    "message": "{\"@timestamp\":\"2015-02-10T17:38:07Z\",\"@fields\":{\"method\":\"GET\",\"path\":\"/faoareas/4\",\"status\":\"200\",\"size\":\"3471\",\"duration\":0.001689}}"
  },
  "_score": 0.26455426,
  "_id": "AUt0kc7s-gODqlF1zfdW",
  "_type": "logs",
  "_index": "logstash-2015.02.10"
}
```

**Comment by sckott** [comment]
and digging into the actual feedback from API requests

```
http 'http://localhost:9200/logstash-2015.02.10/_search?q=timestamp&size=3&pretty=true' | jq ' .hits | .hits[] | ._source | .message | .'

"{\"@timestamp\":\"2015-02-10T17:39:06Z\",\"@fields\":{\"method\":\"GET\",\"path\":\"/\",\"status\":\"302\",\"size\":\"-\",\"duration\":0.000986}}"
"{\"@timestamp\":\"2015-02-10T17:38:03Z\",\"@fields\":{\"method\":\"GET\",\"path\":\"/taxa/\",\"status\":\"200\",\"size\":\"1225\",\"duration\":0.00736}}"
"{\"@timestamp\":\"2015-02-10T17:38:07Z\",\"@fields\":{\"method\":\"GET\",\"path\":\"/faoareas/4\",\"status\":\"200\",\"size\":\"3471\",\"duration\":0.001689}}"
```

**Comment by sckott** [comment]
Some more things to keep track of:
- [x] parameters passed in the query
- [x] IP address
- [x] add timezone to timestamp (already in UTC)
- [x] query run time (pretty sure this is already in there, though need to specify this may not be total resolution time, which depends on how fast the JSON is rendered, internet connection speed, etc)
- [x] log `user-agent` or similar

**Comment by cboettig** [comment]
Very cool! Didn't know anything about elasticsearch before. Nice to see
there's already an official dockerized version too, so will be super easy
to plug into our setup: https://registry.hub.docker.com/_/elasticsearch/

Wondering if we should anonymize IP addresses on the fly by just resolving
them to the city & country?

Should we consider logging anything about how long the query took to
return? Could help us pinpoint performance bottlenecks?

I wonder if we can log anything about the software making the query; e.g.
can you tell if a query comes from rfishbase vs curl command vs something
else?

**Comment by sckott** [comment]
@cboettig  updated the list above. in the rfishbase pkg, you could add `user-agent = rfishbase` to `GET` requests, in addition to what's already passed, e.g., on my machine right now `User-Agent: curl/7.37.1 Rcurl/1.95.4.5 httr/0.6.1`, so maybe with rfishbase added in `User-Agent: curl/7.37.1 Rcurl/1.95.4.5 httr/0.6.1 rfishbase/0.3`

**Comment by sckott** [comment]
@cboettig i put changes for logging in the `logging` branch so we can get the details worked out for Logstash and Elasticsearch installation done before merging to master

and see if you think the stuff put in the log is good - everything you listed except maybe software is implemented (though like I said you could maybe put user agent in rfishbase requests)

**Comment by sckott** [comment]
the IP handling uses freegeoip.net, they say 

> You're allowed up to 10,000 queries per hour by default. Once this limit is reached, all of your requests will result in HTTP 403, forbidden, until your quota is cleared. The freegeoip web server is free and open source so if the public service limit is a problem for you, download it and run your own instance.

so we can host our own if needed, but i really doubt that

**Comment by cboettig** [comment]
Excellent, will try and take a look soon.

Yup, sounds like freegeoip should be fine.  Though with rfishbase it would
be possible for someone to make a single query that loops over a couple API
calls that must be made on a per-species basis, and thus hit the limit.
 e.g. let's get a table of vulnerability for the class Actinopterygii:

## uses 1 API call and then caches the taxa table so future calls don't

need more API calls:
some_fish <- species_list(Class="Actinopterygii")

length(some_fish) # 31454

## needs an api_call per species in some_fish.

species_info(some_fish, fields="Vulnerability")

Of course these all come from the same IP, so presumably the code would
need to look up the georef each time. Do we need to cache IPs to avoid
causing this to involve over 30,000 calls to look up the same IP address?

**Comment by sckott** [comment]
@cboettig looks like they provide a docker image https://github.com/fiorix/freegeoip#docker-image making thing easier perhaps 

hmmm, could maybe just install this docker image and call internally on the server?

**Comment by cboettig** [comment]
Works for me.  All the same seems like it would be worth doing some
temporary caching of IP here to avoid repeated requests to geo-locate the
same IP.  We may also need that data to aggregate requests into a
meaningful layer -- e.g. distinguish between use cases in which one IP is
hitting a lot of API calls vs actually having a lot of different users.

**Comment by sckott** [comment]
Right, good point about needing to cache. 

trying this locally, any idea how to make a port from a docker container be exposed to the host (my mac). Seems to work perfectly with your rocker images, but weird that this one doesn't https://registry.hub.docker.com/u/fiorix/freegeoip/

**Comment by cboettig** [comment]
Hmm, it's a pity that there image is not an automated build or an official
container; generally that's a possible security risk because you just pull
down some binary they have build locally and it is thus less obvious what
is in it (docker inspect helps though).  More trivially, it also means I
cannot look at the Dockerfile.  From the readme it seems like using 8080
should work, just like 8787 does in the rocker containers.

Things get slightly more tricky if you are trying to access the service
from inside another docker container.  Generally, the approach here is not
to expose the port to the outside world, but simply link it internally.
E.g. this is what we do with Redis & MySQL now, you'll see we don't run
mysql with a -p 3306:3306 option.

Ideally I'd think we'd use the same linking strategy to make the port from
freegeoip available to the container running sinatra, which would be the
only container with a port exposed to the outside world.

If you're inside a container and need to access something that is exposed
on localhost on the host machine, this requires an extra level: you need to
use docker's ip address instead of localhost: e.g. see:
http://stackoverflow.com/questions/24319662/, no idea if boot2docker needs
an extra step or not. But then this isn't the preferred solution and
wouldn't be necessary on a web-server where things aren't on localhost:
anyway.

AH, just found what I presume to be their dockerfile:
https://github.com/fiorix/freegeoip/blob/master/Dockerfile
They don't have an EXPOSE 8080 which may be why you can't see the port,
though I would have thought it would be okay using -p 8080:8080.

Long story short: maybe we should stick with the free hosted version for
now? If we do it right, 10000 cap shouldn't matter.

**Comment by sckott** [comment]
Thanks @cboettig - that all makes sense. I did try exposing with `... -p 8080:8080` but didn't work, probably b/c as you said not in their dockerfile i guess. 

Right, okay, let's just try using the web API for freegeoip, and cache results, most people will make queries from just a few places probably, and we're not likely to have more than a few hundred users?

**Comment by sckott** [comment]
- [x] Add caching to geoip addressing acquisition

**Comment by cboettig** [comment]
Okay, all done and dockerized via Pull #22
