### ISSUE TITLE
What tables do I need for basic aquarium information?

### ISSUE THREAD

**Issue by emodev4** [ropensci/fishbaseapi#151]
For example
https://www.fishbase.se/Summary/SpeciesSummary.php?id=271&lang=english

most of the info I'm looking for can be found in the Environment section

"Freshwater; brackish; benthopelagic; pH range: 6.0 - 8.0; dH range: 5 - 19; potamodromous (Ref. 51243); depth range 0 - 20 m (Ref. 6898). Subtropical; 0°C - 41°C (Ref. 35682); 53°N - 22°N"

some of this info is found in the species table, but what about stuff like pH range, dH range, and water temperature?

also is the table info previously found at https://fishbase.ropensci.org/docs available anywhere?

**Comment by cboettig** [comment]
The API has migrated to S3, see https://github.com/ropensci/fishbaseapi/blob/master/README.md
