### ISSUE TITLE
API calls return a 403 error

### ISSUE THREAD

**Issue by gerhardvr26** [ropensci/fishbaseapi#152]
All API calls return a 403 error. I even tested from https://fishbaseapi.readme.io/reference/comnames by clicking on the Try it button just to make sure I'm not doing anything wrong.

**Comment by satan87** [comment]
I got the same issue. Can anyone please look at it?

**Comment by cboettig** [comment]
Thanks, the API has migrated to S3, see updated readme: https://github.com/ropensci/fishbaseapi/blob/master/README.md
