### ISSUE TITLE
Is the API working?

### ISSUE THREAD

**Issue by gerardreches** [ropensci/fishbaseapi#158]
I was trying to test it, but I couldn't get a response other than "Access denied".

**Comment by cboettig** [comment]
See: https://github.com/ropensci/fishbaseapi#fishbase-api

also maybe let us know what commands you are using.

**Comment by cboettig** [comment]
See: https://github.com/ropensci/fishbaseapi#fishbase-api

also maybe let us know what commands you are using.

**Comment by gerardreches** [comment]
> See: https://github.com/ropensci/fishbaseapi#fishbase-api
> 
> also maybe let us know what commands you are using.

<img width="1442" alt="Screenshot 2023-04-29 at 03 44 51" src="https://user-images.githubusercontent.com/7549815/235217410-cfe756d1-2071-4c1e-b7cd-d60fb666868b.png">

In the docs themselves, if you try to run an endpoint, it will throw the error.

**Comment by cboettig** [comment]
Yes, as the readme notes, those docs are deprecated, that API does not exist any more, the current access is limited only to the S3 bucket.

**Comment by gerardreches** [comment]
> Yes, as the readme notes, those docs are deprecated, that API does not exist any more, the current access is limited only to the S3 bucket.

Do we have any example on how to use it?
