### ISSUE TITLE
Reference source for most updated version of Parquet files

### ISSUE THREAD

**Issue by alessandro-russo** [ropensci/fishbaseapi#159]
@cboettig,

could you please clarify where to find the most updated version of Parquet files for FishBase and SeaLifeBase?
Concretely, should we look at the files reachable from https://fishbase.ropensci.org/fishbase (or /sealifebase) or those in your [rfishbase_board](https://github.com/cboettig/rfishbase_board) repo?

Should we assume that the files in https://fishbase.ropensci.org/fishbase are the same as the latest version in [rfishbase_board](https://github.com/cboettig/rfishbase_board) (2023-05, as of today)? It doesn't seem to be the case now (files in https://fishbase.ropensci.org/fishbase were LastModified on 2023-12-31, so I may think that they are "more recent" than the 2023-05 version...).

Thanks!!!

**Comment by cboettig** [comment]
Please consult the schema.org metadata, https://github.com/ropensci/rfishbase/blob/master/inst/prov/fb.prov, which is also used by rfishbase.  Note that the metadata includes sha checksums, applications should rely on checksums to know if versions are the same as other sources or not.  (Note that some tables remain unchanged between releases, and thus have the same checksum.  rfishbase relies on checksums to access files and not download files that are identical to those previously downloaded).  

and yeah, I think we're due for a new release, I'll ping the FishBase team and see if we can get that in the queue!

**Comment by alessandro-russo** [comment]
Many thanks for the clarification and for pointing to the reference metadata!
