### ISSUE TITLE
Status 403

### ISSUE THREAD

**Issue by shi-rudo** [ropensci/fishbaseapi#160]
when doing 

```go
func main() {

	url := "https://fishbase.ropensci.org/species?limit=10&offset=0"

	req, _ := http.NewRequest("GET", url, nil)

	req.Header.Add("Accept", "application/vnd.ropensci.v6+json")

	res, _ := http.DefaultClient.Do(req)

	defer res.Body.Close()
	body, _ := io.ReadAll(res.Body)

	fmt.Println(string(body))

}
```

I get `<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><BucketName>species</BucketName><Resource>/species</Resource><RequestId>17BC1525528D61FF</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>
`

No token or other authentication mechanism is mentioned in the documentation.

**Comment by cboettig** [comment]
sorry we were doing some updates and this went down.  Try now.
