### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by VaSmitka** [ropensci/fishbaseapi#161]
I am trying to acces, but it response:

<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>InvalidAccessKeyId</Code>
    <Message>The Access Key Id you provided does not exist in our records.</Message>
    <BucketName>species</BucketName>
    <Resource>/species</Resource>
    <RequestId>17CF8199C597E274</RequestId>
    <HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId>
</Error>

Please what type of the access key have I need?

**Comment by cboettig** [comment]
can you use the R package?  https://github.com/ropensci/rfishbase

**Comment by cboettig** [comment]
The direct REST endpoints should be back up now, see README
