### ISSUE TITLE
DRY out the API script a bit?

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#19]
@sckott Now that it seems like we've somewhat pinned down a standard pattern for defining endpoints, would it be worth functionalizing the API a bit more (I think you suggested this a bit earlier).   I'm getting to the point where it would be convenient to add a bunch more endpoints but don't want to do a bunch of copy-paste that will make more work for you later, so thought I touch base on this first.  I'm happy either way, just want to follow your lead here.

**Comment by sckott** [comment]
yes, definitely want to DRY things. I'll work on that right away so we can keep moving

**Comment by sckott** [comment]
okay, DRYed evertying exept the `/taxa` route which is a bit more complicated

**Comment by sckott** [comment]
should be easier to add now

**Comment by cboettig** [comment]
Looks great, thanks! Yeah, no worries about taxa/ since that endpoint works
differently anyhow

**Comment by sckott** [comment]
cool, im sure we can do more DRYing, so ill leave this open for now

**Comment by cboettig** [comment]
Changes have been great so far.  Wondering if we might just DRY out the addition of endpoints completely, so that a new endpoint which uses the template:

```
  get '/comnames/?' do
    key = rediskey('comnames', params)
    if redis_exists(key)
      obj = get_cached(key)
    else
      obj = get_new_noids(client, key, 'comnames', params)
    end
    return give_data(obj)
  end
```

could just be given as `add_endpoint("comnames)`?  Also wondering if we should just make the correspondence of endpoint name to table name 1:1 for now?  Long-term we might provide more sensible endpoint names (probably with more sensible endpoint behavior too).

**Comment by cboettig** [comment]
(eg meaning more sensible than the crazy post-it-note style tables currently in place in the sql database; given the crazy SQL schema the API is quite sensible)

**Comment by sckott** [comment]
- `1:1` for `routes:table names` : sure, sounds good, i can do that
- sure, simplifying even more is great, we'll see how far it can go

**Comment by sckott** [comment]
closing, reopen if you think we need to do more
