### ISSUE TITLE
Which tables need api routes?

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#2]
@cboettig curious what tables you think would be good to have routes on?  or are you mostly interested in replicating what the package already does, and the routes are secondary?

**Comment by cboettig** [comment]
The ones in the package that use HTML scraping are all ones that have been added on request, so they would be good things to support (will have to check which tables they correspond to). Looks like those functions are:
- [x] ecology_from_html.R  
- [ ] enviro-climate-range.R  
- [x] fao_area.R
- [x] fooditems.R  
- [x] getPredators.R  
- [x] length-weight-table.R 
- [x] metabolism.R

**Comment by sckott** [comment]
added faoareas in ddce1c2d47a8611c6f6dfac8392ad694ecf83d07

**Comment by sckott** [comment]
@cboettig Did  you want API endpts for each of those above in the list?  Or did you actually mean access to those tables, then you'd take care of combining data on the R side?

**Comment by cboettig** [comment]
Right, I was just thinking access to the relevant tables and we would
combine on the R side.  Less efficient that way but also lighter on the
server & just more familiar.  We can then revisit doing more preprocessing
later to reduce the number of api calls needed & avoid as much joining in R.

**Comment by sckott** [comment]
@cboettig Okay, I'll comment out those methods that do joins, etc. and just give access to the tables needed

**Comment by cboettig** [comment]
Compare this list to the list of tables shown on each species summary page: https://github.com/ropensci/rfishbase/issues/36

As usual, the map between manual, the website, and the SQL tables is hardly 1:1:1, but anyway...

Here's a quick overview of the main tables as extracted from the [FishBase Manual](http://www.fishbase.org/manual/english/contents.htm).

**Key:**
- [x] means we've implemented the API endpoint 

*\* means prioritized endpoint

### NOMENCLATURE
- [x] [The SPECIES Table](http://www.fishbase.org/manual/english/fishbasethe_species_table.htm)
- [x] The COMMON NAMES Table
- [x] [The SYNONYMS Table](http://www.fishbase.org/manual/english/fishbasethe_synonyms_table.htm)

### DISTRIBUTION
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_stocks_table.htm">The STOCKS Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_faoareas_table.htm">The FAOAREAS Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_faoareas_ref_table.htm">The FAOAREAS REF Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_countries_table.htm">The COUNTRIES Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_countref_table.htm">The COUNTREF Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_Introduction_table.htm">The INTRODUCTIONS Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_occurrences_table.htm">The OCCURRENCES Table</a>
- [ ] <a href="http://www.fishbase.org/manual/english/fishbasethe_expeditions_table.htm">The EXPEDITIONS Table</a>

### FAO STATISTICS
- [ ] <a href="http://www.fishbase.org/manual/english/fishbasefao_statistics00002679.htm">FAO Statistics</a>
- [ ] <a href="http://www.fishbase.org/manual/english/fishbasefao_statistics00002679.htm#catches">FAO Catches</a>
- [ ] <a href="http://www.fishbase.org/manual/english/fishbasefao_statistics00002679.htm#aquaculture">FAO Aquaculture</a>

### POPULATION DYNAMICS
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_popchar_table.htm">The POPCHAR Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_length_weight_table.htm">The LENGTH-WEIGHT Table</a> **
- [x] <a href="http://www.fishbase.org/manual/english/lengthfrequency.htm">The LENGTH-FREQUENCY Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/PDF/FB_Book_CBinohlan_Length-Length_RF_JG.pdf">The LENGTH-LENGTH Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_popgrowth_table.htm">The POPGROWTH Table</a>
- [ ] <a href="http://www.fishbase.org/manual/english/fishbasethe_recruitment_table.htm">The RECRUITMENT Table</a>

### TROPHIC ECOLOGY
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_ecology_table.htm">The ECOLOGY Table</a> **
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_food_items_table.htm">The FOOD ITEMS Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_diet_table.htm">The DIET Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_ration_table.htm">The RATION Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_popqb_table.htm">The POPQB Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_predators_table.htm">The PREDATORS Table</a>

### REPRODUCTION
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_reproduction_table.htm">The REPRODUCTION Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_maturity_table.htm">The MATURITY Table</a>
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_spawning_table.htm">The SPAWNING Table</a>

### [ICHTHYOPLANKTON](http://www.fishbase.org/manual/english/fishbaseichthyoplankton00002705.htm)

### [MORPHOLOGY AND PHYSIOLOGY](http://www.fishbase.org/manual/english/fishbasemorphology_and_physiology.htm)
- [x] <a href="http://www.fishbase.org/manual/english/fishbasethe_morphology_table.htm">The MORPHOLOGY Table</a>
- [ ] <a href="http://www.fishbase.org/manual/english/fishbasethe_vision_table.htm">The VISION Table</a>
- [ ] <a href="http://www.fishbase.org/manual/English/PDF/FB_Book_RFroese_Brains_RF_28062010_JG.pdf">The BRAINS Table</a>
- [x] <a href="http://www.fishbase.org/manual/English/PDF/FB_Book_ATorres_Oxygen_11Jul11.pdf">The OXYGEN Table</a>
- [x] <a href="http://www.fishbase.org/manual/English/PDF/FB_Book_ATorres_Swimming_Speed_RF_JG.pdf">The SWIMMING and SPEED Tables</a>
- [ ] <a href="http://www.fishbase.org/manual/english/fishbasethe_gill_area_table.htm">The GILL AREA Table</a>
- [ ] <a href="http://www.fishbase.org/manual/english/fishbasethe_processing_table.htm">The PROCESSING Table</a>

### [GENETICS AND AQUACULTURE](http://www.fishbase.org/manual/english/fishbasegenetics_and_aquaculture00002719.htm)

### [Other Tables](http://www.fishbase.org/manual/english/fishbaseother_tables.htm)
- [References Table](http://www.fishbase.org/manual/english/fishbasethe_references_table.htm)

**Comment by cboettig** [comment]
Not suggesting that we need to implement all of them, but just putting this down here as a placeholder to help group and prioritize, as well as track what we already have.  I'll try and update and annotate the above list to highlight things we want to prioritize or ignore, etc.  

The data is pretty messy so the R implementation to return some clean tidy data.frames is always going to lag substantially behind the API anyway.  I hope to have a suitable set of backbone functions and then hopefully we can encourage contributions for data cleaning routines associated with a particular call.

**Comment by sckott** [comment]
@cboettig nice, those table urls don't seem to resolve for me :(

And do the check marks mean that we should have api routes for each table?

**Comment by cboettig** [comment]
@sckott heh, welcome to FishBase.  Just keep trying to refresh and I think most of the links should work. good illustration of why scraping the website was a terrible idea.  

I've started to check off ones I think we have, and add `**`'s to the ones I think we should prioritize.  (Clearly I should be making better use of Github emoji things here -- edits welcome!)

**Comment by sckott** [comment]
okay, thx, makes sense

**Comment by cboettig** [comment]
@sckott You raise a good question about naming conventions for endpoints on https://github.com/ropensci/rfishbase/issues/31#issuecomment-73368519 

I see your point about having good REST names, but it's a bit tricky here since we don't have control over the naming conventions of the SQL schema & tables but will want the API to be consistent / familiar with them anyway. The FishBASE manual lists six tables in the population dynamics group above, so it might not be obvious that `populations` refers to popGrowth.  We might be best off making the correspondence between the API endpoint and the SQL table 1:1, at least for endpoints which are essentially access to those particular tables.  It's not super nice because the way the tables are organized is something of a mess, but I worry that things will just be more opaque if we rename them.  does that make sense?

I'm trying to come up with good names for the higher-level functions implemented in the R package, most of which will need more than one SQL call to return something meaningful instead of just a bunch of reference codes to other tables anyway.  It would be great to get your input on those names.

It may make sense to make some of those handled on the server end with their own endpoints, which could reduce the number of API queries.  Not sure if the increased computation on the server side instead of the client side would outweigh the benefit though, particularly since whatever server this may end up on will probably be relatively underpowered, while doing the manipulation client-side in R with dplyr is pretty efficient.  (If the API were powering a website where the computational power client-side was way less than what it is in R, doing these computations on the server may make more sense).

**Comment by sckott** [comment]
@cboettig is this updated with all endponts avail. in the api?

**Comment by cboettig** [comment]
I think I've kept it up-to-date so far

**Comment by sckott** [comment]
@cboettig k, just curious
