### ISSUE TITLE
Stability / Error handling

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#23]
Might be good for the app to be robust to any of the non-essential components going down or not responding?  This would also allow a user to deploy without things like the redis and/or logstash containers if they'd prefer.
- [ ] recover option to skip handle a failed attempt to connect to redis, which would also need to trip some kind of flag to avoid any later calls to cache or read from cache I think.
- [ ] similarly for logging, though I suppose logs could be written locally
- [ ] might be good to be able to turn off logging completely?

**Comment by sckott** [comment]
Is there any way to pass options to docker to toggle these things? or better to do in a config file?

Right, so be able to skip caching and logging, and turn off logging completely

**Comment by sckott** [comment]
@cboettig  how do you like the approach so far by having variables set at the top of the `api.rb` file? see https://github.com/ropensci/fishbaseapi/blob/master/api.rb#L11-L12

**Comment by cboettig** [comment]
:+1:
