### ISSUE TITLE
nginx / login-only settings for elasticsearch and kibana?

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#24]
Do we want secure credentials to be required for login access to the elasticsearch api?

I think the best way to do this would be a nginx layer with a CA certificate; since that should allow the API to work under programmatic calls without the user having to click / authenticate stuff, as long as they had the secure CA certificate installed on their machine.

**Comment by sckott** [comment]
yeah, seems best to secure these services

**Comment by sckott** [comment]
see also #43
