### ISSUE TITLE
Kibana needs manual configuration

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#25]
```
docker exec -ti fblogstash bash
apt-get update && apt-get install -y vim-tiny
cd /opt/logstash/vendor/kibana
vi config.js
```

Find the line that has the server address as http://127.0.0.1 and change to match your external server address.

**Comment by sckott** [comment]
thanks!

**Comment by cboettig** [comment]
This is probably just necessary because of my ignorance about logstash config, but have checked in with the docker image maintainer here: https://github.com/pblittle/docker-logstash/issues/56

**Comment by sckott** [comment]
I think we talked about not really supporting/dealing with kibana, closing, reopen if needed @cboettig
