### ISSUE TITLE
error handling / recovery wrt redis

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#26]
Should we handle failures of `get_cached` in error handling with a rescue method that would just repeat the call?  e.g. I think something like this would fall-back successfully if either `redis` call failed.  

``` ruby
get '/species/?:id?/?' do
    key = rediskey('species', params)
    begin
      if redis_exists(key)
        obj = get_cached(key)
      else
      obj = get_new_ids(client, key, 'species', 'SpecCode', params)
      end
    rescue
      obj = get_new_ids(client, key, 'species', 'SpecCode', params)
    end
    return give_data(obj)
  end
```

(related to #23)

**Comment by sckott** [comment]
nice, working on this now locally..

**Comment by cboettig** [comment]
@sckott is this still an issue?  Now that we resolved that UTF-8 encoding I'm not often hitting errors so not sure if they are being cached.

**Comment by sckott** [comment]
@cboettig yeah, i think we're okay now, closing
