### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#3]
down the road, would be great to have caching, e.g. w/ redis https://rubygems.org/gems/sinatra-redis

**Comment by sckott** [comment]
http://www.railsillustrated.com/blazing-fast-sinatra-with-memcached.html

**Comment by sckott** [comment]
memcached ruby gem `dalli` https://github.com/mperham/dalli

**Comment by sckott** [comment]
http://stackoverflow.com/questions/8486596/best-way-to-cache-a-response-in-sinatra

**Comment by sckott** [comment]
@cboettig Okay, i implemented caching in one route locally, and it seems to work - using redis.  

Is redis easy enough to setup with docker?  - see branch [caching](https://github.com/ropensci/fishbaseapi/blob/caching/api.rb#L273-L303)

**Comment by cboettig** [comment]
Yup, should be. Will just connect over TCP like mysql I think

**Comment by sckott** [comment]
Okay, should I go ahead and implement across all routes and merge to master?

**Comment by cboettig** [comment]
lemme just clone the caching branch first and add the appropriate host/port
info to the api file there.  Once I'm sure I can deploy with redis on
docker we can merge.  Should just need a moment to test the docker config
though, so feel free to go ahead and implement across all routes

**Comment by cboettig** [comment]
@sckott Okay, I added a redis container to the the fig.yml and added the configuration to the API in 56b521ee9bdf39c1ff4ed760d2005f7a1650f5fc

(Oh, I didn't add an if clause this time so you should just set those environmental variables appropriately (e.g. to `localhost` and `6379` or some-such.)

Not quite sure how to test if the caching is working, but at least the server is still functioning with the redis container now attached, so you can go ahead and merge to master without breaking anything.  Nice work setting this up!

**Comment by sckott** [comment]
Awesome, I'll written on the rest tomorrow
