### ISSUE TITLE
DO box 

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#36]
@cboettig 

So we currently have `discuss.ropensci.org` on a 1 GB droplet . A few thoughts:

Will we run into any trouble with serving the API from the same server as the discussion forum since `discuss.ropensci.org` is mapped to that servers IP address, and I think port 80.  Can we map `<server.ip.address>:80` to a domain name e.g., `fishbaseapi.org`  exposing only the fishbase API, and not allow exposing the forum?

Box size: currently on a 1 GB droplet at $10/mo - If we decide we need more room, the next one up is 2 GB at $20/mo - I guess we should decide what resources we'll need first, then adjust the box size accordingly. The discussion forum i think takes up very little resources right now since there is little activity.

**Comment by sckott** [comment]
since we are only hosting the fishbase API temporarily (correct?) then maybe its worth just using a separate box to avoid any conflict with the forum, maybe on a 2GB box ?

**Comment by sckott** [comment]
@cboettig part of reason i'm asking is i was gonna install the api on the box were using for the forum but want to clear up what we want here

**Comment by cboettig** [comment]
Yeah, all good questions. Right, we're hosting only temporarily so I think
a clean box might be best here. In any event the costs aren't gonna be
huge, even if we run a 2 GB box for a few months.  @karthik, thoughts?

**Comment by sckott** [comment]
yeah, a clean 2GB box seems good. I tested yesterday on a 4GB box, hitting it with large requests in a loop, and it all handled it easily, so i imagine 2GB is fine.

**Comment by cboettig** [comment]
p.s. mapping to different ports is easy, no need to use port 80. I've added an env var at the top of `docker.sh` to make this easier.

Not sure how the mapping of domain names part goes, can you map domain names to specific ports? Is that done at the server level (say, nginx) or the DNS level?

**Comment by sckott** [comment]
nice, didn't know we could use a different port (makes sense though) 

don't know about domain names. karthik set it up for the forum. I think he linked the sub domain name and the IP for the server with the hosting provider for `ropensci.org`

i think we can use the DO web interface or API to set up domain name if we wanted ? e.g, https://www.digitalocean.com/community/tutorials/how-to-set-up-a-host-name-with-digitalocean

**Comment by karthik** [comment]
> . In any event the costs aren't gonna be huge, even if we run a 2 GB box for a few months.  @karthik, thoughts?

Looks like a 2 gig box will cost $20 a month. How long are we hoping to run this for? and for whom? Will fishbase or someone else be able to pick up the cost?

> don't know about domain names. karthik set it up for the forum. I think he linked the sub domain name and the IP for the server with the hosting provider for ropensci.org

I can map any subdomain to an IP, but can't forward to any unexposed ports. That has to happen on the server side.

**Comment by sckott** [comment]
@cboettig can you ask if Fishbase folks would pay for a few months of server time while we are in the testing phase? if not, i can pay with my own money - the convenience is worth it

**Comment by cboettig** [comment]
Okay, I've written to them, will let you know when/what I hear back.
Otherwise, I can chip in to the costs

**Comment by sckott** [comment]
thanks carl!

**Comment by karthik** [comment]
Great. I think it's silly for us to bear this cost (even though we could). I don't know the full context with this current API set up but we are providing the developer time pro bono. The least the data provider can do is pick up some of the actual server expenses. Neither of you should be paying out of pocket.

**Comment by sckott** [comment]
don't think we need this open any longer

**Comment by cboettig** [comment]
btw, I did write and hear back from them -- they are negotiating cloud space for fishbase.org too, but don't have the details yet.  Hoping we will hear back soon.  They didn't comment about covering our dev costs, but given the limited resources I doubt they can cover costs for our development.

**Comment by sckott** [comment]
since it's on my account, i'm fine covering costs for a few months  - @cboettig if you think we can get away with a smaller box then we can do $10/month, half the price
