### ISSUE TITLE
moving log file location

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#37]
Hey @sckott ,

Trying to get the logstash to work with kibana URL being configured at runtime instead of the crazy solution in #25.  I should just be able to pass in the name of the server as the env var `ES_HOST` when running the logstash container, but for some reason doing so is causing the logstash container to crash.  

Apparently the problem may be due to writing logs (and thus having to link volume of) `/root` (which is `~` since api runs as root on the docker container). See: https://github.com/pblittle/docker-logstash/issues/56

I tried to switch the location of the logfile to `/var/log/fishbase/api.log` but it does not seem to be writing logs now, even though it is creating the file:  (see https://github.com/ropensci/fishbaseapi/blob/master/api.rb#L13 and https://github.com/ropensci/fishbaseapi/blob/master/api.rb#L100).  And for some reason, linking this volume instead still causes a crash.

**Comment by sckott** [comment]
Bummer. I looked around a bit on blogs and such and couldn't find anything useful to solve this. And can you access Elasticsearch?  Cant seem to get to port 9200

**Comment by cboettig** [comment]
Does the ruby code look right to you?  I can probably get the others up if
it is

**Comment by sckott** [comment]
looking

**Comment by sckott** [comment]
so i assume logs should be in the logstash container? so in this file https://github.com/ropensci/fishbaseapi/blob/master/logstash.conf#L3  ? if so, that file is empty. Or am I looking in the wrong place

**Comment by cboettig** [comment]
Originally the ruby script wrote logs to `~/fishbaseapi.logs` (which is the
same as `/root/fishbaseapi.logs`) and so logstash would read them from
there (because the logstash container would share the volume `/root` with
the api container).  I've reverted to this setup on master, still need to
check if it's working.

I had moved the location of the file to `/var/log/fishbase/api.log` (e.g. I
tried to set the ruby script to write to this new location, and the linked
the volume `/var/log/fishbase` instead, since that's what the logstash
container maintainer suggested).  This setup is still in place on the
fix-logstash branch.

The branches thing doesn't work quite as smoothly since we pull
logstash.conf from master instead of using the local file, which is why I
was originally pushing changes to master.  (to avoid having to manually
edit the url in docker.sh differently for each branch).  I think I can get
this to use the local file instead of the online file to avoid this issue.

But for the first step, now that master is back to how it was, let's see if
we can get the logs generated at all in their original location (~/).  Like
you say, could be a unicorn problem.

**Comment by sckott** [comment]
Right, i couldn't seem to get using a local logstash.conf file to work with docker - works locally on my machine, but not with docker - hopefully it's not a problem to use the remote file

**Comment by cboettig** [comment]
Can you tell me more about what works locally?  e.g. running with unicorn
or with ruby / webrick?

**Comment by sckott** [comment]
playing locally more...

**Comment by sckott** [comment]
@cboettig Martin says he uses this ruby gem https://rubygems.org/gems/logstash-logger 

seems if we get that to work we can maybe do away with the logstash container all together which would be nice since it takes up a lot of resources. 

nevermind, still uses logstah, hmmm

here's an example of someone using it in sinatra https://github.com/danmayer/server_responder/blob/master/app.rb#L48-L54

**Comment by sckott** [comment]
@cboettig closing as I think we have this sorted, reopen if it's not
