### ISSUE TITLE
compression

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#4]
http://nginx.org/en/docs/http/ngx_http_gzip_module.html

**Comment by sckott** [comment]
@cboettig now that we have nginx setup, do we already have gzip compression turned on?

**Comment by cboettig** [comment]
[Our nginx.conf](https://github.com/ropensci/fishbaseapi/blob/master/nginx.conf#L28) is just largely based on the default, so we have this off for now, but feel free to edit the nginx.conf to turn it on.  I know very little about nginx conf details really, so not sure what the tradeoffs are on such features, but if anything sounds worthwhile or at least worth experimenting with, go for it.  Certainly compression seems like a good idea.

**Comment by sckott** [comment]
okay, I'll give it a try

**Comment by sckott** [comment]
`Rack::deflater` seems to be a common rack middleware way to do compression https://github.com/rack/rack/blob/master/lib/rack/deflater.rb

but its not clear if this is an alternative to doing compression with nginx, or an additional step...?

**Comment by sckott** [comment]
@cboettig okay, not completely sure i've done this correctly, but now you can do 

``` sh
~$ curl -v  --header "Accept-Encoding: gzip" 'http://104.236.176.205/species'

> GET /species HTTP/1.1
> User-Agent: curl/7.37.1
> Host: 104.236.176.205
> Accept: */*
> Accept-Encoding: gzip
>
< HTTP/1.1 200 OK
* Server nginx/1.7.9 is not blacklisted
< Server: nginx/1.7.9
< Date: Tue, 17 Feb 2015 01:36:03 GMT
< Content-Type: application/json; charset=utf8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< Status: 200 OK
< Cache-Control: public, must-revalidate, max-age=60
< X-Content-Type-Options: nosniff
< Content-Encoding: gzip
<
```

which I think is correct, but we're not getting the `Content-Encoding: gzip` when the accept-encoding header isn't passed with the request

``` sh
~$ curl -v 'http://104.236.176.205/species?limit=900&fields=speccode' > stuff.json

> GET /species HTTP/1.1
> User-Agent: curl/7.37.1
> Host: 104.236.176.205
> Accept: */*
>
< HTTP/1.1 200 OK
* Server nginx/1.7.9 is not blacklisted
< Server: nginx/1.7.9
< Date: Tue, 17 Feb 2015 01:37:00 GMT
< Content-Type: application/json; charset=utf8
< Content-Length: 31472
< Connection: keep-alive
< Vary: Accept-Encoding
< Status: 200 OK
< Cache-Control: public, must-revalidate, max-age=60
< X-Content-Type-Options: nosniff
<
```

and it seems that that field present in the response header suggest gzipping is working http://www.nginxtips.com/how-to-configure-nginx-gzip-compression/ but maybe that's not true, will keep looking

**Comment by cboettig** [comment]
Cool. so does this mean we should be passing that header in all the httr calls from rfishbase, or is it happening automatically?

**Comment by sckott** [comment]
i'm not sure yet, still need to play around some more. Seems that other APIs do the compression automatically without the client needing to send an accept header, which i imagine want to avoid. BUT - i should check as I did set a variable that says only gzip when content greater than X length...so small requests wouldn't be compressed

**Comment by cboettig** [comment]
Interesting, see the top answer here: http://stackoverflow.com/questions/15999606/enable-gzip-compression-with-nginx

looks like the modern browsers accept the compression automatically but we probably need to manually add this to the headers in the API requests...  Unless @hadley already enables gzip compression in httr GET requests by default...

**Comment by sckott** [comment]
right, i thought browser did it automatically, easy to set this by default within rfishbase :)

**Comment by hadley** [comment]
httr should do it by default

**Comment by cboettig** [comment]
@hadley you rock, as always.

**Comment by sckott** [comment]
i think we're all set on this
