### ISSUE TITLE
unit testing

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#40]
Might be worth thinking if there's any kind of testing we can run here?  

Might look more like queries against the testing API instance than actually deploying the API here (though I suppose the tests on rfishbase2.0 rather fulfill that role already).  Or perhaps we could have a dummy SQL database with no real data, for testing purposes only. 

The docker calls can all be run on circle.io.

**Comment by sckott** [comment]
There is an issue for testing the Sinatra application #16 - which would test the app, but not the docker steps - but a you said, those can be done on circle.io 

Good point that rfishbase will do some testing. 

Worth having tests since it's always better to have tests, but also will help make a better app that we can reuse for other purposes

**Comment by sckott** [comment]
sinatra testing link http://www.sinatrarb.com/intro.html#Testing

**Comment by cboettig** [comment]
for a first pass, maybe we can have a quick testing file like at that link that just checks that each endpoint in `heartbeat` doesn't 500 err

**Comment by sckott** [comment]
@cboettig Okay, got tests running locally, you can run those yourself by doing `rake test TESTOPTS='-v'` (or `rake test`)

Note, more tests should be written, but it's a start

Though not sure how to get tests running on Travis - see latest attempt https://travis-ci.org/ropensci/fishbaseapi/builds/68613674

Ideally, we could test the whole app, database and all from travis - perhaps we can hook into it on the DO server with use of secure keys?

Or at least somehow just test against the `fishbase.ropensci.org` - can look into see if this is possible

**Comment by cboettig** [comment]
Cool!

  Maybe from Travis we should just test if all the endpoints are up &
returning the expected data?  Guess that's not really unit testing the Ruby
code so much as just checking the app is up, but would still be useful and
would need any auth or anything on the Travis side

On Sat, Jun 27, 2015, 9:34 AM Scott Chamberlain notifications@github.com
wrote:

> @cboettig https://github.com/cboettig Okay, got tests running locally,
> you can run those yourself by doing rake test TESTOPTS='-v' (or rake test)
> 
> Note, more tests should be written, but it's a start
> 
> Though not sure how to get tests running on Travis - see latest attempt
> https://travis-ci.org/ropensci/fishbaseapi/builds/68613674
> 
> Ideally, we could test the whole app, database and all from travis -
> perhaps we can hook into it on the DO server with use of secure keys?
> 
> Or at least somehow just test against the fishbase.ropensci.org - can
> look into see if this is possible
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ropensci/fishbaseapi/issues/40#issuecomment-116095857
> .
> 
> ## 

http://carlboettiger.info

**Comment by sckott** [comment]
yeah, doing that now, just testing remote

**Comment by sckott** [comment]
@cboettig Any chance we can run the test suite of the complete app in circle.io ?

**Comment by cboettig** [comment]
@sckott tricky to download and import the database each time for testing; not sure if it would run fast enough to complete before the ci job got terminated (~ 50 mins).  Also at the moment that part still isn't completely automated, due to issues with docker/scripting mysql which I don't quite understand

**Comment by sckott** [comment]
Okay, I have remote testing running on travis now, e.g., https://travis-ci.org/ropensci/fishbaseapi/builds/68886616  

The Rakefile has https://github.com/ropensci/fishbaseapi/blob/testing/Rakefile two test suites you can run, one for the server API itself, and the other for the local Sinatra application. Run remote by `rake remote TESTOPTS='-v'` and local by `rake local TESTOPTS='-v'`

Still can add more tests for both suites, I'll get remote filled out first - but should we merge this to master?

**Comment by cboettig** [comment]
Very cool. yup, let's merge this into master.

Um, stupid question, but trying to see what the tests actually are/what
they do? Looks like maybe a get request against every route?
https://github.com/ropensci/fishbaseapi/blob/testing/test_fxns.rb , is that
right?

On Mon, Jun 29, 2015 at 3:19 PM Scott Chamberlain notifications@github.com
wrote:

> Okay, I have remote testing running on travis now, e.g.,
> https://travis-ci.org/ropensci/fishbaseapi/builds/68886616
> 
> The Rakefile has
> https://github.com/ropensci/fishbaseapi/blob/testing/Rakefile two test
> suites you can run, one for the server API itself, and the other for the
> local Sinatra application. Run remote by rake remote TESTOPTS='-v' and
> local by rake local TESTOPTS='-v'
> 
> Still can add more tests for both suites, I'll get remote filled out first
> - but should we merge this to master?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ropensci/fishbaseapi/issues/40#issuecomment-116862976
> .
> 
> ## 

http://carlboettiger.info

**Comment by sckott** [comment]
Tests are in `/spec` https://github.com/ropensci/fishbaseapi/tree/testing/spec

The Rakefile has two tasks, one for remote server API only tests (`remote`) and one if you want to test the sinatra app locally `local`, There's two helper files in root dir for testing that get used in files in `/spec`

**Comment by cboettig** [comment]
ah! that's awesome

On Mon, Jun 29, 2015 at 3:32 PM Scott Chamberlain notifications@github.com
wrote:

> Tests are in /spec
> https://github.com/ropensci/fishbaseapi/tree/testing/spec
> 
> The Rakefile has two tasks, one for remote server API only tests (remote)
> and one if you want to test the sinatra app locally local, There's two
> helper files in root dir for testing that get used in files in /spec
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ropensci/fishbaseapi/issues/40#issuecomment-116866577
> .
> 
> ## 

http://carlboettiger.info
