### ISSUE TITLE
mangled json responses

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#41]
Hey @sckott ,

Occasionally I will get the following error message (e.g. on a large call such as: "http://fishbaseapi.info/taxa?family=&limit=40000", though it happens occasionally on smaller calls as well)

```
Error in parseJSON(txt) : parse error: trailing garbage
           "Actinopterygii"     }   ] }HTTP/1.1 500 Internal Server Er
                     (right here) ------^
```

If you put that link into a browser you will probably get the same thing -- a long field of valid JSON that suddenly terminates with the HTTP error message.  Because the header is intact, `httr` etc see the return as response code 200 and continue, and the error doesn't occur until the JSON parser attempts to parse the content and freaks out. 

Any idea why this error is ending up in the JSON output like this?  Or ideas on how to avoid it?

**Comment by sckott** [comment]
hey carl, yeah, i think i've seen this before, though it was an anomaly, but apparently not. 

My initial guess is that it has to do with redis caching, but I'll take a look

**Comment by sckott** [comment]
@mfenner here's what the mangled bottom of the response looks like, from this example:

http://fishbaseapi.info/taxa?limit=10000

```
... cutoff 

      "Class": "Actinopterygii"
    }
  ]
}HTTP/1.1 500 Internal Server Error
```

**Comment by sckott** [comment]
@cboettig played a bit more tonight, tinkered with mysql, but i doubt it comes from there since why would mysql return http errors. it throws errors, but why would they be http errors

**Comment by mfenner** [comment]
@sckott, my first guess is a server error that is not handled properly, something I have seen sometimes in various JSON APIs (a variation is a error response in html rather than json). In `api.rb` I only see a route for 404 errors, but I don't see how the other errors are handled.

To give you one example how I do this in Rails: https://github.com/articlemetrics/lagotto/blob/master/app/controllers/concerns/authenticable.rb#L72-L75. You see that I use the ActiveSupport `rescue_from` to rescue errors in controllers and return a meaningful response. In Sinatra you would use `halt` (and you are doing this for 404 errors), see http://myronmars.to/n/dev-blog/2012/01/why-sinatras-halt-is-awesome for a discussion.

Tests are a good way to make sure your API properly handles errors, e.g. wrong or missing query parameters, etc.

**Comment by sckott** [comment]
@mfenner Right, forgot about specifying `halt` rules for other http errors - was focused on trying to see where that errant string is coming from. I'll add a `halt` for 500 and see what that does

**Comment by cboettig** [comment]
Scott, good point, though on the server MySQL is connected to the api
container via a network (TCP ip) port, not a socket like you are using
locally, not sure if http errors apply in that context

**Comment by sckott** [comment]
hmm, tried martins suggestion of adding a 500 error handler, but didn't seem to change anything - trying another change

for mysql, if that's the case, would be nice to test mysql on the server, know how to connect to mysql command line in the mysql container?

**Comment by sckott** [comment]
@cboettig okay, adding 500 handlers didn't' do anything

**Comment by mfenner** [comment]
I think you should see different errors if there is a problem with the MySQL connection. Is your error handler giving you enough information to track down what is wrong?

**Comment by sckott** [comment]
@mfenner hmmm, i don't know for sure. I'm not sure how to simulate 500 errors locally to make sure it works, ill check more

**Comment by mfenner** [comment]
Ideally you do this with a testing framework. I use `rspec`, but you could also use `minitest`. Then add `Rack::Test`, and possibly `Webmock` and/or `vcr`. You can then test all the different conditions (different query parameters, errors, etc.). API testing is one of the areas where writing tests is straightforward and rewarding,

**Comment by sckott** [comment]
Thanks Martin, we do plan to get tests set up ( #40 ), should have done it earlier!  I like `vcr` - i've even started to port `Webmock` and `vcr` to R since together they would be useful in R

**Comment by sckott** [comment]
:+1:
