### ISSUE TITLE
Set maximum value for limit parameter

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#42]
to 5000 for now

**Comment by cboettig** [comment]
nice. Do we also have a offset parameter then?  

I'm not quite clear how this works in the context of the table join (for the `/taxa` endpoint).  It seems you would have to compute the full join  first before you knew how many results would be returned?  Maybe it's not an issue

**Comment by sckott** [comment]
yeah, haven't pushed up changes yet with offset parameter

**Comment by sckott** [comment]
havne't implemented in the taxa table yet...will think about that

**Comment by sckott** [comment]
so now we get an error when limit is over the max

```
http://fishbaseapi.info/species?limit=5005

HTTP/1.1 400 Bad Request
Cache-Control: public, must-revalidate, max-age=60
Connection: keep-alive
Content-Length: 61
Content-Type: application/json
Date: Wed, 25 Feb 2015 19:27:15 GMT
Server: nginx/1.7.9
Status: 400 Bad Request
X-Content-Type-Options: nosniff

{
    "error": "invalid request",
    "message": "maximum limit is 5000"
}
```
