### ISSUE TITLE
Use freegeoip docker image?

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#47]
There is a docker image - i tested locally, works nicely https://registry.hub.docker.com/u/allingeek/docker-freegeoip/ - this might be better than relying on a web api?

**Comment by cboettig** [comment]
sweet, will plug it in.

**Comment by sckott** [comment]
in this case, we get rid of the geolocater gem and just call to that container

**Comment by cboettig** [comment]
I've added it to the docker-geoip branch.  From the container where the Ruby code is running, the service should now be available at: `geoip:8080`.  I guess you have some idea how to replace the `geolocater` calls with CURL calls against that IP?

**Comment by cboettig** [comment]
Um, looks like you might rather use an existing `freegeoip` gem to query against that server, e.g. https://github.com/lmumar/freegeoip-ruby

just do: 

``` ruby
Freegeoip.setup :host => 'geoip', :port => '8080', :protocol => 'http'
```

instead of `127.0.0.1` as the host.

**Comment by sckott** [comment]
nice! that sounds good

**Comment by cboettig** [comment]
I think I should close this issue since we're using the freegeoip image, and then I'll open a new issue for the fact that it isn't actually getting the IPs in the first place.
