### ISSUE TITLE
Route on api that redirects to the documentation

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#48]
E.g., Martin has Lagotto setup so that `alm.plos.org/api` redirects to the docs (see http://alm.plos.org/api)

We could have e.g., `fishbaseapi.info/docs` redirect to http://docs.fishbaseapi.apiary.io with a simple 

``` ruby
get '/docs' do
    redirect 'http://docs.fishbaseapi.apiary.io'
end
```

**Comment by cboettig** [comment]
:+1:
