### ISSUE TITLE
Devise plan for shuttling elasticsearch log data elsewhere

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#49]
Since security is an issue with elasticsearch, we could use ES's snapshot and restore tools http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-snapshots.html that should allow us to create backups that we can easily `scp` or similar to our own machines, load into ES locally, and explore...

**Comment by cboettig** [comment]
I think we just need to secure ES properly behind https with a CA certificate (unsigned/self-signed, because otherwise costs big $) in NGINX.  This is pretty straight forward, I've done this for a docker registry before but haven't gotten around to it here.  I can take a quick stab at it now
