### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#5]
Possibly RAML - useful = ? https://github.com/coub/raml_ruby

Swagger looks easiest, trying that

**Comment by sckott** [comment]
Started to play with both swagger and apiary, 

apiary docs started here: http://docs.fishbaseapi.apiary.io/# ping @cboettig

**Comment by cboettig** [comment]
Apiary is looking great!  I remember being annoyed at some swagger docs
recently, but forget exactly why.  nice work.

**Comment by sckott** [comment]
i do like how swagger is machine readable json, i tried that, but apiary markdown format specification would be easier for non-techy types to maintain in the long term, and it looks nice

**Comment by sckott** [comment]
@cboettig updated the apiary docs, see http://docs.fishbaseapi.apiary.io/#

you can now try the api using the root `fishbaseapi.info` and it should work

added info on response codes, pagination, etc.

**Comment by sckott** [comment]
Okay, most recent docs now in the `api_docs.md` file in this repo https://github.com/ropensci/fishbaseapi/blob/master/api_docs.md - I think makes sense to get a apiary or other interactive console done later, when we're more set on the API design - 

I'll update `api_docs.md` file as we go, closing for now
