### ISSUE TITLE
Inline/API-based documentation of endpoints?

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#51]
Hey @sckott,

Keep feeling it would be nice to have some inline documentation of the endpoints and I'm wondering if just editing the `heartbeat` list directly is the best way to do this.  It's nice to get a table of endpoints and all, but at minimum it would be useful to have a description of what the endpoint does; (particularly since using the fishbase SQL table names helps in programming, but makes it all the harder to know what an endpoint with a name like `intrcase` actually returns).  Thoughts?

**Comment by sckott** [comment]
@cboettig sounds good, i haven't seen this very often, but I guess don't see why not. 

Do you mean this in place of the html documentation?  I'm working on a swagger version so it's all within this repo and all open source, but we will have to serve it up from within the droplet

**Comment by cboettig** [comment]
I guess I'm really looking for the roxygen equivalent for ruby API,
something so that I  don't have to flip between different pages to remember
what this or that endpoint was doing.  Not sure if it's common for
endpoints to include any description of themselves.  I have seen other APIs
have an endpoint that describes other endpoints with more detail than just
a listing there names; kinda handy for dev work since you can query the API
instead of going to the website, but probably not a good idea if it means
maintaining multiple copies of the same documentation

**Comment by sckott** [comment]
Is this the kind of thing you had in mind? http://demo.ckan.org/api/3/action/package_search?q=spending  Of course you can just ignore the `help` element in a client library

There are a few things that might help if we wanted to autogenerate docs https://github.com/ddollar/sinatra-croon and https://github.com/rkh/yard-sinatra

**Comment by cboettig** [comment]
sure, any of these look good but I'm happy to follow your lead on whatever
you think is best.  Might be easiest to just go with swagger anyway.

**Comment by sckott** [comment]
I vote for swagger or something like that. Have set up in part the swagger document, but not tried to get it running on the server yet.

**Comment by sckott** [comment]
we'll stick with markdown docs for now in this repo
