### ISSUE TITLE
fix geolocation of IP

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#52]
API does not seem to be correctly identifying the ip address in the first place, all ips in the log come back as the docker ip.  

Once this is fixed, logs need to switch over to actually doing the geolocation and reporting the anonymized location instead of the ip address.

**Comment by sckott** [comment]
Seems that all IP addresses are the same too, seems like we're just getting the container IP possibly?

**Comment by cboettig** [comment]
Okay, I believe this is fixed.
