### ISSUE TITLE
JSON-API standard-ish

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#53]
@cboettig  http://jsonapi.org/ interesting - if there's something that is getting adoption, we could consider modifying our responses

**Comment by cboettig** [comment]
Nice! Cool that it's a registered MIME type already: "JSON API has been properly registered with the IANA. Its media type designation is application/vnd.api+json."

**Comment by sckott** [comment]
@cboettig I guess easiest is to just leave response as it is now, and modify response based on accept headers, e.g.., `application/vnd.api+json`

**Comment by cboettig** [comment]
as a side note is kind of funny to see json re-invent xml bit by bit --
these mime types are essentially simplified XML schemas; just with a bit
more attempt to be general from the start and minus the ability to mix and
match them / share namespaces.  But it's all about getting the right
balance between simple, flexible, and formal/predictable structure anyway,
so it's probably progress.

**Comment by sckott** [comment]
don't think we're going to get to this, closing
