### ISSUE TITLE
Elasticsearch fail behavior

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#55]
Wonder if there's a way to not lose old indices (each day's collection of logs) when the container crashes. E.g., today @cboettig you put it back up, but we only have today's index. However, it's weird, cause it had data only from back in April, and we know there's been requests since then

**Comment by cboettig** [comment]
Weird.  We're linking the local log file, which is still there, has entries
ranging from 2015-04-02 until today.  (see
/home/cboettig/log/fishbase/api.log  on the server).  Somehow Elasticsearch
must not be reading in the whole log?

**Comment by sckott** [comment]
Okay, that's good news that they are there.

**Comment by cboettig** [comment]
Hmm, nothing obviously wrong in the configuration that I can see.  elasticsearch has the log here: https://github.com/ropensci/fishbaseapi/blob/master/logstashconf/logstash.conf#L3

weird that it would be able to read in the recent stuff but not the earlier stuff; should all be in the same file.

**Comment by cboettig** [comment]
@sckott can you check this again when you get a chance? no idea if I've got this part configured correctly now, but I did mess with some stuff today

**Comment by sckott** [comment]
yeah, i think we gotta wait a few days (so we have a few days of logs) AND have the service taken down then put back up  (so we see if it recovers correctly), can do then

**Comment by sckott** [comment]
we're not using ES anymore, correct?  @cboettig if so, i'll close this

**Comment by cboettig** [comment]
Yup
