### ISSUE TITLE
ecosystems route seems to not exist, or be broken somehow

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#56]
`/ecosystems/` gives a 500 server error, which is a catch all, so not sure what's wrong yet

**Comment by sckott** [comment]
@cboettig  we need to manually update the container on the server, right?

**Comment by cboettig** [comment]
right, I should just need to pull the git repo and run `docker.sh`, will do now

**Comment by sckott** [comment]
looks like it's working now, so this should close ropensci/rfishbase#54 ?

**Comment by cboettig** [comment]
Yup thanks. (got my issue numbers transposed in my commit msg)

On Fri, Jun 26, 2015 at 12:51 PM Scott Chamberlain notifications@github.com
wrote:

> looks like it's working now, so this should close ropensci/rfishbase#54
> https://github.com/ropensci/rfishbase/issues/54 ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ropensci/fishbaseapi/issues/56#issuecomment-115853767
> .
> 
> ## 

http://carlboettiger.info
