### ISSUE TITLE
Raw documentation of data (table defs, columns defs, units)

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#62]
Regardless of if/how the documentation is presented (e.g #5; though perhaps that just focuses more on defining the API itself than really documenting properties of the data), we will want a machine-readable way to store the documentation of each endpoint; that is, a description of each table and a description of each column, along with the units involved.  (Um, EML is an obvious candidate to express this, but having this in a plain spreadsheet is probably both more flexible and convenient for data entry and reuse).

**Comment by cboettig** [comment]
@sckott We should take a look and see what (if any) of this information may be embedded in the SQL itself?  It seems some SQL systems may include such help text; haven't looked into this for fishbase. (e.g. http://stackoverflow.com/questions/15161505/use-a-query-to-access-column-description-in-sql). 

At very least the SQL records the object type (logical/character/integer/numeric/id and so forth) which is lost in the conversion to JSON.  Ideally we'd be able to preserve those types directly but maybe that's not possible e.g. does JSON have a notion of type or is everything a string?  Otherwise we might want the type information to be included in the documentation block for the column/field.

**Comment by sckott** [comment]
Right, agreed on needing a machine readable documentation mechanism

I'll have a look and see if we can get useful info from the SQL tables into the json output, I know JSON-LD has the concept of metadata around data records, but I'll see if what we can do with simple JSON first

**Comment by sckott** [comment]
@cboettig here's additional info from the schema we're using in the `/listfields` route:

``` r
tbl(src, sql("SELECT * FROM information_schema.`columns` C WHERE TABLE_SCHEMA = 'fbapp' limit 1")) %>% data.frame

  TABLE_CATALOG TABLE_SCHEMA TABLE_NAME COLUMN_NAME ORDINAL_POSITION COLUMN_DEFAULT IS_NULLABLE DATA_TYPE CHARACTER_MAXIMUM_LENGTH
1           def        fbapp     abnorm     AutoCtr                1           <NA>          NO       int                       NA
  CHARACTER_OCTET_LENGTH NUMERIC_PRECISION NUMERIC_SCALE DATETIME_PRECISION CHARACTER_SET_NAME COLLATION_NAME COLUMN_TYPE COLUMN_KEY
1                     NA                10             0                 NA               <NA>           <NA>     int(11)        PRI
           EXTRA                      PRIVILEGES COLUMN_COMMENT
1 auto_increment select,insert,update,references 
```

Seems like all we can really use form that is the data type field, seem right?

**Comment by cboettig** [comment]
yup, and I think that information is available at the table level already.  Oh well, no surprise I guess.  Maybe I should ask the fishbase folks to be sure, though I'm guessing the [Fishbase Manual](http://www.fishbase.org/manual/english/contents.htm) is all there is by way of documentation.

**Comment by cboettig** [comment]
@sckott I added a .csv file containing documentation for most of the tables we have endpoints for: https://github.com/ropensci/fishbaseapi/blob/master/docs/docs-sources/tables.csv

Do you think you can wrap this into the API such that we have an endpoint that will return this as a JSON object of tables, where each table has a description and a link?  

The descriptions are pretty rough so far, mostly taken from the FishBase manual pages (which are linked in the links column), but we can revise as we go along / with user feedback.

The bigger task is getting descriptions of all the columns for each table, and more immediately, how to make those available.  Do you think we should have separate endpoints for each, or just pull all of that information into the same documentation endpoint?  Some tables only have a few columns, but some have many; and each column would at least need a description and a probably a unit (maybe also a data type).

**Comment by sckott** [comment]
@cboettig nice, thanks for doing that. I started to do this, but oscon got in the way. 

Yes, I think we can simply just have a route that gives the csv as json back. Do you want to replace this with the current `/listfields` route ? Or an additional route?

> Do you think we should have separate endpoints for each, or just pull all of that information into the same documentation endpoint?

We could do something very RESTy like:
- `/tables/ecology`
- `/tables/countref`
- `/tables/diet`

That way `/tables` (or whatever it's called) is just adding 1 route really . I suppose `/tables` would return all then.

**Comment by cboettig** [comment]
No, I think `listfields` is still useful to search for fields, particularly as it may be some time before we have all fields documented. 

I like the RESTy format, but maybe it should be `/docs/ecology` etc?  and `docs` just returns the descriptions of the tables themselves (the csv I added), while `/docs/ecology` defines all the fields, units, etc in the ecology table?

**Comment by sckott** [comment]
Ah, right, `/docs` makes more sense. And makes more sense to return the description of the tables.

**Comment by sckott** [comment]
@cboettig Okay, pushed first run at `/docs`, just reads the csv file

Where does the data come from for each table. e.g, where does data come from for a call to `/docs/countref` ? From a manually created file/json blob, or from the SQL DB?  I imagine manual?  Should we just start with generating a json blob or csv for each table from the SQL DB, then edit those files?

**Comment by cboettig** [comment]
Good question.  My idea was to just have the docs as separate .csv files in the fishbaseapi repo (e.g. `/docs/docs-sources` path, like `tables.csv`.  Yeah, a database might make more sense then just parsing .csv, but my hope is that users will find it easier to edit/correct/extend .csv files.  Does that make sense?

**Comment by sckott** [comment]
By the way, here's example of `/docs` call

``` sh
HTTP/1.1 200 OK
Access-Control-Allow-Methods: HEAD, GET
Access-Control-Allow-Origin: *
Cache-Control: public, must-revalidate, max-age=60
Connection: keep-alive
Content-Length: 14454
Content-Type: application/json; charset=utf8
Server: thin
X-Content-Type-Options: nosniff

[
    {
        "description": "API endpoint to confirm that the API is up. Lists all available endpoints",
        "links": null,
        "table": "heartbeat"
    },
    {
        "description": "API endpoint to test the status of the database",
        "links": null,
        "table": "mysqlping"
    },

...
```

**Comment by cboettig** [comment]
:+1: LGTM

**Comment by sckott** [comment]
Yeah, makes sense to have csv files. I can get those started

**Comment by sckott** [comment]
Okay, added csv files for all tables, each just has table and column name in each row of output

``` sh
http 'localhost:3000/docs/species'
```

``` sh
HTTP/1.1 200 OK
Access-Control-Allow-Methods: HEAD, GET
Access-Control-Allow-Origin: *
Cache-Control: public, must-revalidate, max-age=60
Connection: keep-alive
Content-Length: 6936
Content-Type: application/json; charset=utf8
Server: thin
X-Content-Type-Options: nosniff

[
    {
        "column_name": "SpecCode",
        "table_name": "species"
    },
    {
        "column_name": "Genus",
        "table_name": "species"
    },
    {
        "column_name": "Species",
        "table_name": "species"
    },
    {
        "column_name": "SpeciesRefNo",
        "table_name": "species"
    },

... continued
```

**Comment by cboettig** [comment]
perfect, nice work

On Fri, Jul 24, 2015 at 4:30 PM Scott Chamberlain notifications@github.com
wrote:

> Okay, added csv files for all tables, each just has table and column name
> in each row of output
> 
> http 'localhost:3000/docs/species'
> 
> HTTP/1.1 200 OK
> Access-Control-Allow-Methods: HEAD, GET
> Access-Control-Allow-Origin: *
> 
> Cache-Control: public, must-revalidate, max-age=60
> Connection: keep-alive
> Content-Length: 6936
> Content-Type: application/json; charset=utf8
> Server: thin
> X-Content-Type-Options: nosniff
> 
> [
>     {
>         "column_name": "SpecCode",
>         "table_name": "species"
>     },
>     {
>         "column_name": "Genus",
>         "table_name": "species"
>     },
>     {
>         "column_name": "Species",
>         "table_name": "species"
>     },
>     {
>         "column_name": "SpeciesRefNo",
>         "table_name": "species"
>     },
> 
> ... continued
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ropensci/fishbaseapi/issues/62#issuecomment-124765619
> .
> 
> ## 

http://carlboettiger.info

**Comment by sckott** [comment]
seems like we've sorted this out, @cboettig re-open if not
