### ISSUE TITLE
Update sealifebase with new things in fishbase?

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#65]
@cboettig should we port over the `/docs` and `/listfields` routes to sealifebase?  And any other improvements to sealifebase?  Or do you want to take that case by cases basis

**Comment by cboettig** [comment]
Yup, porting those sounds good.  

Since the database schema is the same, much of the doc file contents may be able to carry over too.

We may need other improvements eventually, but I haven't had a chance to explore the sealifebase database enough to know what it will need. Guess we take our queues from users and/or anything that pops up in fishbase side that looks like it would transfer over.

**Comment by sckott** [comment]
Okay, I can move over `/listfields` and `/docs`

p.s. well, it's not exactly the same, e.g., https://github.com/ropensci/fishbaseapi/commit/107a0fff5266a84bf6797efe6f2e656682341a10 there's no `GenCode` field in the `Species` table in sealifebase DB, whereas there is in fishbase DB

**Comment by cboettig** [comment]
ha! guess I'm not surprised; no doubt we (or more likely our users) hit other schema differences that break other things, guess we just fiddle as we go along.  

Presumably it would be possible to just generate some summary of the whole database schema that could be compared?  Might also help us deal with updates like when whole tables go missing (e.g. https://github.com/ropensci/rfishbase/issues/55)

**Comment by sckott** [comment]
right, could use that SQL query line to get all tables and fields, then `git diff` each table (and maybe also the schema)

**Comment by sckott** [comment]
@cboettig how did you make this file https://github.com/ropensci/fishbaseapi/blob/master/docs/docs-sources/tables.csv  We need equivalent for sealifebase

**Comment by cboettig** [comment]
Completely manually; e.g. copy-pasting bits from the FishBase manual into the spreadsheet. Not even sure where the manual is for sealifebase.

**Comment by sckott** [comment]
hmm, any thoughts on what to give for the main `/docs` route then for sealifebase

**Comment by cboettig** [comment]
for now, maybe just point to the fishbase version, tables.csv.  The generic descriptions will be mostly accurate

**Comment by sckott** [comment]
okay, `/docs` and `/listfields` routes added to sealifebase, `/docs` for sealifebase is just the table names for now

hmm, but `/sealifebase/listfields` not working, investigating

**Comment by sckott** [comment]
fixed
