### ISSUE TITLE
Prevent SQL injection

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#7]

**Comment by karthik** [comment]
You could regexp out anything but the input, but at this point I'm sure someone has written a Ruby gem that will sanitize input.

**Comment by sckott** [comment]
right, seems like the best practice is to use _prepared statements_ e.g. http://stackoverflow.com/questions/2258781/preventing-sql-injection-good-ruby-method - seems pretty simple

**Comment by cboettig** [comment]
@sckott is this still an issue?

**Comment by sckott** [comment]
@cboettig i think it still could be - someone could _i think_ include a drop table potentially - i'll take a look

**Comment by cboettig** [comment]
We may also just be able to mount the database as a read-only file; e.g. just change the file permissions for the mysql user....

**Comment by sckott** [comment]
interesting, good thinking

**Comment by sckott** [comment]
pretty much done with this now that we're using activerecord
