### ISSUE TITLE
Add endpoint to access/download images of fish

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#70]
(user request)

**Comment by sckott** [comment]
Do you have some example URLs for images?

And how would users use the route?  I assume they'd need to pass in a ID (uuid, or something else) for the images?

Also, we/vulcan folks aren't hosting images, right?  So I guess we can have the route, and 303 redirect to the right place

**Comment by cboettig** [comment]
I think they might actually have images in one of the SQL tables but
haven't checked recently

On Thu, Oct 8, 2015, 5:18 PM Scott Chamberlain notifications@github.com
wrote:

> Do you have some example URLs for images?
> 
> And how would users use the route? I assume they'd need to pass in a ID
> (uuid, or something else) for the images?
> 
> Also, we/vulcan folks aren't hosting images, right? So I guess we can have
> the route, and 303 redirect to the right place
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ropensci/fishbaseapi/issues/70#issuecomment-146722861
> .
> 
> ## 

http://carlboettiger.info

**Comment by sckott** [comment]
you mean links right, not images themselves
