### ISSUE TITLE
Provide dumps of an entire endpoint via API

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#73]
from #71 -
- Does fishbase prefer we don't do this?  
- From an API design standpoint, I at least don't see this kind of thing in an API, but some may
- Seems like dumps would be better to provide from S3 perhaps

**Comment by sckott** [comment]
thoughts @EvilScott @cboettig on this?

If people are interested in dumps of a lot of data, for example for a whole route, 1) does Fishbase want to allow that from this API, 2) if Fishbase is okay with it, is that something an API would do, or better to serve via S3 (with automated pushes to S3 when we get updated SQL dumps)

**Comment by MollsReis** [comment]
This kind of data dump is best served via an independent S3 download. Just be mindful of bandwidth costs.

**Comment by sckott** [comment]
Thanks, glad I was on the right track. Now to see if Fishbase want to allow it.

**Comment by sckott** [comment]
@cboettig Do you know if Fishbase folks are interested in allowing any kind of dumps via S3?

**Comment by cboettig** [comment]
No idea, but we should ask.  

Just cc'd you on a follow up to that user email yesterday, in which FishBase folks highlight that some of the tables aren't really up-to-date anyway. Not sure if that would influence there willingness to have people downloading by dump.

**Comment by sckott** [comment]
closing for now, can reopen later if Fishbase is okay with slash there's a big need for it
