### ISSUE TITLE
docs endpoint down /missing since transition?

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#76]

**Comment by sckott** [comment]
hmm, `/docs/:table` is there though,

**Comment by cboettig** [comment]
interesting.  but there used to be an overall docs endpoint with summaries of each table I think too...

**Comment by sckott** [comment]
Looking at the old code

**Comment by sckott** [comment]
Code is all there, just not reading the table correctly when `/docs` is called, debugging locally

**Comment by sckott** [comment]
it may be that the `tables.csv` file has non-ascii text in it

**Comment by sckott** [comment]
`/docs/occurrence` is 404'ing, but hopefully that just requires the update database?

**Comment by sckott** [comment]
Hmmm, I think i fixed the non-ascii problem, but now stack trace gives `<CSV::MalformedCSVError: Missing or stray quote in line 35>` -

**Comment by sckott** [comment]
fixed
