### ISSUE TITLE
Unexpected error when specifying fields

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#79]
@sckott @EvilScott Since our merge, some of the API calls are giving me MySQL errors I didn't expect.  For instance:

This call works:

http://fishbase.ropensci.org/spawning?SpecCode=77&limit=200&fields=SpecCode%2CSpecCode%2CJan%2CFeb%2CMar%2CApr%2CMay%2CJun%2CJul%2CAug%2CSep%2COct%2CNov

But add `Dec` to the list of fields and it fails:

http://fishbase.ropensci.org/spawning?SpecCode=77&limit=200&fields=SpecCode%2CSpecCode%2CJan%2CFeb%2CMar%2CApr%2CMay%2CJun%2CJul%2CAug%2CSep%2COct%2CNov%2CDec

with error:

```
{"count":0,"returned":0,"data":null,"error":{"message":"Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Dec FROM `spawning` WHERE `spawning`.`SpecCode` = 77 LIMIT 200' at line 1: SELECT  SpecCode,SpecCode,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec FROM `spawning` WHERE `spawning`.`SpecCode` = 77 LIMIT 200"}}
```

Not sure what is going wrong.  Any ideas?

**Comment by sckott** [comment]
Not sure, I'll take a look soon

**Comment by MollsReis** [comment]
"Dec" is a reserved word in MySQL; just need to wrap the column names with back ticks

**Comment by MollsReis** [comment]
Taking a quick look at the code; this is something I would think ActiveRecord should have handled on its own

**Comment by MollsReis** [comment]
https://github.com/ropensci/fishbaseapi/blob/master/models/base.rb#L23

This #select method should probably be given an array of fields surrounded in backticks. Try something like this:

``` ruby
        .select(params[:fields].map {|f| "`#{f}`" })
```

**Comment by sckott** [comment]
thanks @EvilScott will try taht

**Comment by cpetrik** [comment]
Are there any other reserved words I should be conscious of putting backticks around? Also, do all the calls/functions require fields to be specified now?

**Comment by sckott** [comment]
@cpetrik Are you using this API directly?  I think we can take care of that for you, so you shouldn't have to worry about what fields to backtick and which not, just pass in fields

> do all the calls/functions require fields to be specified now?

no, the default is all fields

**Comment by cpetrik** [comment]
I am using rfishbase with options(FISHBASE_API = "http://fishbase.ropensci.org"). I have been having a few problems. 
- I saved a list of validated names from a month or so ago and now when I try validating them again it comes up NULL.
- when I don't specify fields (fish 121 is Gadus chalcogrammus): 
  spawn<-spawning(fish[121])
  Warning message:
  In error_checks(parsed, resp = resp) :
  Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM `spawning` WHERE `spawning`.`SpecCode` = 318 LIMIT 200' at line 1: SELECT   FROM `spawning` WHERE `spawning`.`SpecCode` = 318 LIMIT 200 for query http://fishbase.ropensci.org/spawning?SpecCode=318&limit=200&fields=

But spawn<-spawning(fish[121],fields=c("Jan","Feb")) works

**Comment by cboettig** [comment]
@cpetrik Thanks. The second error you list should be fixed in the latest dev copy of fishbase,

``` r
install.packages("rfishbase", repo="http://packages.ropensci.org")
```

@sckott the new API doesn't like a blank `&fields=`, even though the old API was okay with it.  Maybe we can strip blank queries to avoid these MySQL syntax errors?

@cpetrik Re the validate names, that's weird.  Can you give me some minimal code to reproduce the example (e.g. a call to validate with a partial list of the species names?)  Thanks!!

**Comment by sckott** [comment]
@cboettig Okay, pushed a change, not on server though. 

My testing shows now allows reserved words given backticks, and does parsing of html escaped input query values. 

@EvilScott can't figure out how to drop query params that are empty/`nil` e.g., specified as `fields=` or `fields` in the url request. Any ideas?

**Comment by cboettig** [comment]
@sckott Nice, thanks!  Feel free to deploy to server when you get a chance. 

Re dropping empty parameters, my guess would be that you might be able to do some parsing/sanitization on request before it gets passed to MySQL to drop them. I suppose you could regex out things like `&\\w+=$` or `(&\\w+=)&` kind of thing, but perhaps there's something less hacky.  Anyway, the patched `rfishbase` client should at least avoid making such requests in future so it's probably not a real issue.

**Comment by sckott** [comment]
@cboettig I can't login to the server, did you change something?

**Comment by cboettig** [comment]
Are you using the IP address?  Try just using fishbase.ropensci.org, and
recall user is ubuntu

On Sat, Nov 21, 2015, 7:04 PM Scott Chamberlain notifications@github.com
wrote:

> @cboettig https://github.com/cboettig I can't login to the server, did
> you change something?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ropensci/fishbaseapi/issues/79#issuecomment-158703833
> .
> 
> ## 

http://carlboettiger.info

**Comment by MollsReis** [comment]
@sckott do you want to open a new issue for dropping empty query params with some examples?

**Comment by sckott** [comment]
sure

**Comment by sckott** [comment]
think this is sorted, reopen if not
