### ISSUE TITLE
Query-able fields?

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#8]
@cboettig what fields should users be allowed to query?  since you're more familiar with the data...

Right now, I've set it up so that users can query on any field. Do you think this is best?  Or do you think only certain fields should be exposed to query on?  If we do limit to only some fields can be queried on that does make it a little easier to solve https://github.com/ropensci/fishbaseapi/issues/7 because we don't have to account for any field queried. 

note that this is different from what gets returned (All fields unless there some reason not to)

**Comment by sckott** [comment]
@cboettig pinging you again so we can get this done - i think we should go with limiting what fields can be queried on, agreed?  then add more as needed

**Comment by cboettig** [comment]
Okay, I think that makes sense; I'll need to go through the functions I have so far and see what fields we query on currently; it's a relatively tiny subset though (usually SpecCode or Species & Genus).

**Comment by sckott** [comment]
okay, cool, yeah, I don't want to break anything

**Comment by sckott** [comment]
@cboettig from #18 seems like you're saying we should restrict queryable fields to `species`, `genus`, and `speccode` - should I implement that now?

**Comment by cboettig** [comment]
@sckott Let's wait till we've done a few more endpoints to be sure that will work.  e.g. looks like it will work for species table, but not for common names or synonyms, where we need to able to query on the common name or synonym itself.

**Comment by sckott** [comment]
right, ok

**Comment by sckott** [comment]
@cboettig updating the docs a bit - since the query-able fields are unlimited right now, I'm only putting in the fields always avail. (`limit`, `offset`, `fields`), and a few other fields that are most likely to be queried on  

e.g. http://docs.fishbaseapi.apiary.io/#reference/list-species

**Comment by cboettig** [comment]
Nice, looks good. yeah, that makes sense for now

**Comment by sckott** [comment]
in the more general discussion area on top in apiary, I can explain that 

> many query params are possible...see output fields for options...but this may change in the future
