### ISSUE TITLE
Error responses are being cached

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#82]
Seems like we should just give back the JSON with error message, and not cache it in Redis, right?

Or am i missing something.

@EvilScott @cboettig

**Comment by cboettig** [comment]
right, that makes sense to me.

**Comment by sckott** [comment]
ah, looks like caching is setup to only cache 200 successful requests https://github.com/ropensci/fishbaseapi/blob/master/api.rb#L44

When I was looking at this a bunch of requests were failing due to Ruby errors, not server errors, so I guess those were being cached as they were returning 200

will look into this more

**Comment by MollsReis** [comment]
Can you give some examples of error URL/responses that have been cached?

**Comment by sckott** [comment]
I've fixed the previous bugs, looking for others

**Comment by sckott** [comment]
hmm, would have thought this would throw an error http response, gives error message at least

```
~$ http 'http://localhost:8080/genera?limit=adsf'

HTTP/1.1 200 OK
Access-Control-Allow-Methods: HEAD, GET
Access-Control-Allow-Origin: *
Cache-Control: public, must-revalidate, max-age=60
Cache-Hit: true
Connection: close
Content-Length: 82
Content-Type: application/json; charset=utf8
Date: Mon, 30 Nov 2015 22:40:09 GMT
Status: 200 OK
X-Content-Type-Options: nosniff

{
    "count": 0,
    "data": null,
    "error": {
        "message": "limit is not an integer"
    },
    "returned": 0
}
```

and this, path doesn't exist

```
~$ http 'http://localhost:8080/genera/asdfasdf'

HTTP/1.1 200 OK
Access-Control-Allow-Methods: HEAD, GET
Access-Control-Allow-Origin: *
Cache-Control: public, must-revalidate, max-age=60
Connection: close
Content-Length: 75
Content-Type: application/json; charset=utf8
Date: Mon, 30 Nov 2015 22:41:01 GMT
Status: 200 OK
X-Content-Type-Options: nosniff

{
    "count": 0,
    "data": null,
    "error": {
        "message": "no results found"
    },
    "returned": 0
}
```

since these are both 200 responses, they get cached.

**Comment by MollsReis** [comment]
It seems to me that the best place to fix this would be changing the status to a 4XX (400 is probably fine) [here](https://github.com/ropensci/fishbaseapi/blob/master/api.rb#L110). IIRC just adding `status 400` as a line inside the `rescue` block should do it.

**Comment by sckott** [comment]
I'll try that
