### ISSUE TITLE
sealifebase taxa endpoint just throws an error

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#84]
Getting an error on: http://fishbase.ropensci.org/sealifebase/taxa

```
{"count":0,"returned":0,"data":null,"error":{"message":"Mysql2::Error: Unknown column 'species.GenCode' in 'field list': SELECT  species.SpecCode, species.Genus, species.Species, species.SpeciesRefNo, species.Author, species.FBname, species.SubFamily, species.FamCode, species.GenCode, species.SubGenCode, species.Remark, families.Family, families.Order, families.Class FROM `species` INNER JOIN families on species.FamCode = families.FamCode INNER JOIN genera on species.GenCode = genera.GenCode LIMIT 10"}}
```

The fishbase version seems okay: http://fishbase.ropensci.org/taxa

Not sure what's going wrong -- are their significant differences between the schemas of sealifebase and fishbase now?  (I believe this endpoint was working prior to #74, but not certain).  

Issue originally reported via https://github.com/ropensci/rfishbase/issues/79

**Comment by sckott** [comment]
Bummer. I'll take a look soon

**Comment by sckott** [comment]
Weird, the column is definitely there 

```
$ http 'http://fishbase.ropensci.org/sealifebase/docs/species' | jq .data[].column_name | grep GenCode
#> "GenCode"
#> "SubGenCode"
```

**Comment by sckott** [comment]
I think I see the problem.  The code for the `/taxa` route for sealifebase was different in the old API, so we need diff. code for `/` vs. `/sealifebase` - I'll see about doing that
