### ISSUE TITLE
count values are not accurate

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#86]
`count` should be the number found in the database, not the number returned, which is what `returned` gives

for some reason in `api.rg` the returned object  is `{ count: data.length, returned: data.length, data: data, error: nil }.to_json`, so `count` and `returned` are the same thing

**Comment by sckott** [comment]
what we used previously to get a count value https://github.com/ropensci/fishbaseapi/blob/dd4927a1d9bad5cbccbd18d6607bb52518c7b7f7/api.rb#L570-L574

**Comment by sckott** [comment]
@EvilScott any ideas on how to do this with ActiveRecord

**Comment by MollsReis** [comment]
@sckott shouldn't be too difficult. what is the expected value? total count of rows in the table? its not really clear what that old method is doing

can you post some example usage/output with desired usage/output in this thread?

**Comment by sckott** [comment]
The expected value is the number of results found for the query given by the user. So it's the same query as passed to get the actual hash/data, but we just want a row count 

e.g., using the Crossref API http://api.crossref.org/works?query=lion&rows=0  we want the value `total-results` from the result

```
{
  status: "ok",
  message-type: "work-list",
  message-version: "1.0.0",
  message: {
   query: {
     search-terms: "lion",
     start-index: 0
   },
  items-per-page: 0,
  items: [ ],
  total-results: 6837,
  facets: { }
 }
}
```

**Comment by MollsReis** [comment]
I'm a bit confused. What's the difference between the number return by the query and the count of the query? I'm not entirely sure what is desired here.

**Comment by MollsReis** [comment]
Here is the ActiveRecord documentation on `#count` http://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-count

**Comment by sckott** [comment]
in the crossref api eg., `total-results` is total number found given the query - but zero results were returned as I set `rows=0` - does that still not make sense

**Comment by MollsReis** [comment]
oh oh oh! i see. so basically count if we weren't providing a limit.

**Comment by MollsReis** [comment]
sorry it took me a moment to grok it; change [this line](https://github.com/ropensci/fishbaseapi/blob/master/api.rb#L110) to:

``` ruby
{ count: data.limit(nil).count(1), returned: data.length, data: data, error: nil }.to_json
```

**Comment by sckott** [comment]
thanks, i'll try that

**Comment by MollsReis** [comment]
sweet :smile_cat:

**Comment by sckott** [comment]
:rocket:
