### ISSUE TITLE
test suite failures

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#88]
@EvilScott any ideas?  https://travis-ci.org/ropensci/fishbaseapi/builds/107916052#L144-L149  

I'm not familiar with nulldb tests, and so not sure where something is going wrong. thoughts?

**Comment by MollsReis** [comment]
its basically a way to stub out the DB dependency. i'll look into it

**Comment by sckott** [comment]
thanks!

**Comment by MollsReis** [comment]
check out #89
