### ISSUE TITLE
get SpecCode from species name (or higher taxonomy)

### ISSUE THREAD

**Issue by cboettig** [ropensci/fishbaseapi#9]
@sckott Do we have a way to get the fishbase SpecCode for a species, given the species name (or similarly, a list of all SpecCodes corresponding to species matching a queried genus, family, etc?)

**Comment by sckott** [comment]
@cboettig three things there i think
- [x] get SpecCode for a species, given species name 
- [x] get list of all SpecCode's corresponding to species matching a queried genus
- [x] get list of all SpecCode's corresponding to species matching a queried family, etc

For the first two, yes:

curl 'http://localhost:4567/species/?genus=Abalistes&species=stellatus&fields=speccode'
curl 'http://localhost:4567/species/?genus=Abalistes&fields=speccode

But for all in a family, etc. we have to do a join since the `species` table only has code for family `FamCode`, though confusingly, does have `SubFamily` name in the table itself -

thoughts?

**Comment by cboettig** [comment]
hmm.  Sounds like we might be best off if we computed a table that had columns of species code, species, genus, family, etc. Then I think it would be one query to return all species codes matching a particular query? (Maybe also for a query that gives multiple species at once?)  Or is that crazy?

**Comment by cboettig** [comment]
Your current taxa table with the join seems to solve this perfectly.  The only thing I'd consider is maybe adding a column for the `FBName` field from the `species` table? This appears to be the accepted fishbase common name.

**Comment by sckott** [comment]
> Sounds like we might be best off if we computed a table that had columns of species code, species, genus, family, etc. Then I think it would be one query to return all species codes matching a particular query? (Maybe also for a query that gives multiple species at once?) Or is that crazy?

is this still a concern, or is your newest comment now supersede that?  

I'll add `FBName` to the output

**Comment by cboettig** [comment]
Yeah, I think it is no longer a concern; just omitting the species & genus
is enough to get a full table join if it is needed. With `FBName` included
I think this table will do everything it needs to do.

**Comment by sckott** [comment]
okay, thx

**Comment by sckott** [comment]
looks like this is done, open again if i'm wrong @cboettig

**Comment by cboettig** [comment]
@sckott Not seeing the field `FBName` in the returns from taxa.  think you might add this?

**Comment by sckott** [comment]
yeah, can do

**Comment by sckott** [comment]
@cboettig looking at that column, its `FBname`, not `FBName`, at least I can't find a `FBName` - they're all null values. Do you expect any values to be non null?

**Comment by cboettig** [comment]
Yeah, could be FBname, sorry.  should be a column of common names, don't
think it should have many (any?) Nulls...

**Comment by sckott** [comment]
@cboettig do you know what table it comes from?

**Comment by cboettig** [comment]
species table

**Comment by sckott** [comment]
yeah, the data in `FBname` are all null's . 

what about `ComName` from the comnames table? could join that table in to get common names

**Comment by cboettig** [comment]
They don't look all NULL to me:

```
mysql> SELECT FBname FROM species WHERE SpecCode=2;
+--------------+
| FBname       |
+--------------+
| Nile tilapia |
+--------------+
1 row in set (0.00 sec)

```

All SpecCodes I've tried return names.  

Right, I'm actually currently doing this using the common names table, but there are many common names for a given spec code, even within a single language (check out http://www.fishbase.us/comnames/CommonNamesList.php?ID=2&GenusName=Oreochromis&SpeciesName=niloticus&StockCode=1).  I just pick the most commonly used one (in English), but that's often but not necessarily the same as the "Fishbase Name" which acts as a kind of "accepted" common name (e.g. it's the name on the species page).

**Comment by sckott** [comment]
I do get the same thing your your SQL query. That is so weird. 

When I do `SELECT FBname FROM species limit 10;` I get all NULLs. But 

```
mysql> SELECT FBname,SpecCode FROM species limit 10;
+-----------------------+----------+
| FBname                | SpecCode |
+-----------------------+----------+
| Giant salmon carp     |    16239 |
| NULL                  |     2347 |
| NULL                  |    62612 |
| Starry triggerfish    |        9 |
| NULL                  |    58334 |
| NULL                  |    62797 |
| NULL                  |    65146 |
| NULL                  |    55145 |
| NULL                  |    55143 |
| Chinese false gudgeon |    22903 |
+-----------------------+----------+
```

weird

**Comment by cboettig** [comment]
Don't you need a `WHERE` statement in the query?

**Comment by sckott** [comment]
hmm, i didn't think so, i'm just taking the `head` basically of first 10 rows

**Comment by sckott** [comment]
anyway, just pushed that commit above, and it does seem to work

**Comment by sckott** [comment]
does that work now @cboettig the `FBname` field output?

**Comment by cboettig** [comment]
Nice, yup, that's working perfectly.
