### ISSUE TITLE
Ignore case completely in fields parameter

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#91]
Is there any reason to care about case at all?  e.g., why not let `SpecCode`, `Speccode`, and `speccode` all work?  Will see if there's any tables with fields with the same name but different cases

**Comment by sckott** [comment]
from ropensci/rfishbase#90

**Comment by cboettig** [comment]
good question, I don't think there's any situation where case matters, so that's probably a good fix

**Comment by sckott** [comment]
cool, will make sure it won't break anything first
