### ISSUE TITLE
sealifebase taxa available in api, but not through web

### ISSUE THREAD

**Issue by jhpoelen** [ropensci/fishbaseapi#97]
When searching for taxa using https://fishbase.ropensci.org/sealifebase/taxa?limit=1 , the response is 

``` json
{"count":119058,"returned":1,"data":[{"SpecCode":70200,"Genus":"Abrocoma","Species":"bennettii","SpeciesRefNo":19,"Author":"Waterhouse, 1837","FBname":null,"FamCode":1254,"Remark":null,"SubFamily":null,"Family":"Abrocomidae","Order":"Rodentia","Class":"Appendicularia"}],"error":null}
```

When attempting to resolve the specode 70200 to a sealifebase page, the related page, http://sealifebase.org/summary/Abrocoma-bennettii.html, displays the following message:

```
This name (Abrocoma bennettii) was downloaded from Catalogue of Life. for more information.
SeaLifeBase currently does not have information on the species (SpecCode = 70200).
If you would like to contribute data, please email sealifebase@fin.ph this entire message. 
Back
```

I would expect that only taxa with associated information would be included in the list of taxa. 

Is there a way to filter out the taxa that do not have any associated information on sealifebase?

Thanks!

This issue is related to https://github.com/GoMexSI/gomexsi-web/issues/73

**Comment by jhpoelen** [comment]
@dengaloo just curious - is this by design (see above)?

**Comment by Dengaloo** [comment]
@jhpoelen yes this means that the name that you are looking for is not yet used in SLB, that is we have not uploaded it from the Catalog of Life. This may mean two things, 1) that the name has a problem and was thus not ingested into our system - meaning that we might need to verify with WoRMs; or 2) that we do not have any information for that species at the moment.

**Comment by Dengaloo** [comment]
@jhpoelen Skit will be able to tell us how we can filter out these scientific names which were not ingested by SLB. I forget the field, but there is one.

**Comment by sckott** [comment]
thanks for the issue @jhpoelen - looks like we can include in the api docs how to filter these out once we know what that field is

**Comment by jhpoelen** [comment]
Having a way to select only the SLB taxa would be great . . . @FIN-JBarile could you please share which field indicates whether a taxon is included in SLB?

**Comment by FIN-JBarile** [comment]
Hi. @jhpoelen You have to link the SPECIES table to the STOCKS table to get the list of names that have more information other than what is available in the SPECIES table. (SELECT SPECIES.SpecCode, SPECIES.Genus, SPECIES.Species
FROM SPECIES INNER JOIN STOCKS ON SPECIES.SpecCode = STOCKS.SpecCode;
)

**Comment by jhpoelen** [comment]
@FIN-JBarile thanks for your suggestion. In order to make this work with the existing fishbase api, I'll have to download all species, all stocks through the ropensci fishbaseapi, and perform the join using some customized code. I cannot execute the query you provided against the web api. ; (. I expect this method to be slow and error-prone. But hey, if that's what we have, that's what I'll work with. 

It would make my life a bit easier if a versioned mysql dump for fishbase/sealifebase were publicly available as an file archive. This way, I would be able to do operations on the species/stock tables without having to retrieve the information through a (slow) web api. Any chance I can convince you to make these archives publicly available?

**Comment by sckott** [comment]
@jhpoelen I don't think our API is really that slow for the proper use cases - it seems like you often want to get all Fishbase data, correct? which is not a good use of a web API

We can edit or create a new endpoint incorporating the SQL statement above to solve the use case here

**Comment by jhpoelen** [comment]
@sckott Yep, most use cases I deal with concern processing _all_ data from a specific source. In this case it is spec codes from Fishbase and SeaLifeBase. And, I also agree that a web api is not really a suitable method for doing these kinds of whole dataset analysis. However, the fishbase api (which is great by the way!) is the only publicly available method to access fishbase data without reverting html scraping.

I think it would be great to include the query suggested by @FIN-JBarile as an endpoint for both fishbase and sealifebase apis. Perhaps a suitable name would be "stockSpecies". I am sure that others would appreciate this functionality. Ideally, the entire taxonomic path would be included (e.g. family, class, order etc) in an attempt to avoid naming conflicts.

Thanks for your prompt reply, curious to hear your thoughts and let me know how I can help.

**Comment by jhpoelen** [comment]
@sckott I took some time to write a tool (see https://github.com/jhpoelen/fishbase_archiver/) that enables batch data processing needed for name linking to fishbase and sealifebase. Curious to hear your thoughts on this. 

Because this tool and the resulting archives allow me to do necessary transformation / joins, I am closing this issue. Thanks all for chiming in!

**Comment by sckott** [comment]
> I think it would be great to include the query suggested by @FIN-JBarile as an endpoint for both fishbase and sealifebase apis. Perhaps a suitable name would be "stockSpecies"

#98

> github.com/jhpoelen/fishbase_archiver/

cool - will have a look, have vacation next week, but when I get back

**Comment by jhpoelen** [comment]
Great - hope you'll have a nice break. Will be out hiking for most of July myself, so no rush on my end, just curious to hear your thoughts at some point.

Also - the api was plenty fast for downloading compressed chunks of 5k rows - nice!

**Comment by sckott** [comment]
> the api was plenty fast for downloading compressed chunks of 5k rows 

oh good!
